create table if not exists public.playtest_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  session_code text not null,
  player_name text,
  case_id text not null,
  case_title text,
  completed_at timestamptz not null default now(),
  summary jsonb not null default '{}'::jsonb,
  resources jsonb not null default '{}'::jsonb,
  triggers jsonb not null default '{}'::jsonb,
  cognition jsonb not null default '{}'::jsonb,
  decision_log jsonb not null default '[]'::jsonb
);
create index if not exists playtest_sessions_completed_at_idx on public.playtest_sessions (completed_at desc);
create index if not exists playtest_sessions_session_code_idx on public.playtest_sessions (session_code);
create table if not exists public.playtest_feedback (
  id bigint generated by default as identity primary key,
  session_id text not null,
  session_code text,
  case_id text,
  feedback jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.app_error_logs (
  id bigint generated by default as identity primary key,
  session_id text,
  session_code text,
  error jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.playtest_sessions enable row level security;
alter table public.playtest_feedback enable row level security;
alter table public.app_error_logs enable row level security;
drop policy if exists "public can read playtest sessions" on public.playtest_sessions;
create policy "public can read playtest sessions" on public.playtest_sessions for select to anon using (true);
drop policy if exists "public can insert playtest sessions" on public.playtest_sessions;
create policy "public can insert playtest sessions" on public.playtest_sessions for insert to anon with check (true);
drop policy if exists "public can insert playtest feedback" on public.playtest_feedback;
create policy "public can insert playtest feedback" on public.playtest_feedback for insert to anon with check (true);
drop policy if exists "public can insert app error logs" on public.app_error_logs;
create policy "public can insert app error logs" on public.app_error_logs for insert to anon with check (true);
