create table if not exists public.playtest_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null,
  run_id text,
  session_code text not null,
  player_name text,
  case_id text not null,
  case_title text,
  completed_at timestamptz not null default now(),
  summary jsonb not null default '{}'::jsonb,
  resources jsonb not null default '{}'::jsonb,
  triggers jsonb not null default '{}'::jsonb,
  cognition jsonb not null default '{}'::jsonb,
  decision_log jsonb not null default '[]'::jsonb
);
alter table public.playtest_sessions add column if not exists run_id text;
create index if not exists playtest_sessions_run_id_idx on public.playtest_sessions (run_id);
create index if not exists playtest_sessions_run_case_idx on public.playtest_sessions (run_id, case_id);
create table if not exists public.playtest_feedback (
  id bigint generated by default as identity primary key,
  session_id text not null,
  session_code text,
  case_id text,
  feedback jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create table if not exists public.app_error_logs (
  id bigint generated by default as identity primary key,
  session_id text,
  session_code text,
  occurred_at timestamptz,
  source text,
  current_case text,
  node_id text,
  error_name text,
  error_message text,
  error_stack text,
  component_stack text,
  dom_snapshot text,
  viewport jsonb not null default '{}'::jsonb,
  context jsonb not null default '{}'::jsonb,
  error jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.app_error_logs add column if not exists occurred_at timestamptz;
alter table public.app_error_logs add column if not exists source text;
alter table public.app_error_logs add column if not exists current_case text;
alter table public.app_error_logs add column if not exists node_id text;
alter table public.app_error_logs add column if not exists error_name text;
alter table public.app_error_logs add column if not exists error_message text;
alter table public.app_error_logs add column if not exists error_stack text;
alter table public.app_error_logs add column if not exists component_stack text;
alter table public.app_error_logs add column if not exists dom_snapshot text;
alter table public.app_error_logs add column if not exists viewport jsonb not null default '{}'::jsonb;
alter table public.app_error_logs add column if not exists context jsonb not null default '{}'::jsonb;
alter table public.app_error_logs add column if not exists error jsonb not null default '{}'::jsonb;
alter table public.playtest_sessions enable row level security;
alter table public.playtest_feedback enable row level security;
alter table public.app_error_logs enable row level security;
drop policy if exists "public can read playtest sessions" on public.playtest_sessions;
drop policy if exists "allow anonymous playtest inserts" on public.playtest_sessions;
drop policy if exists "public can insert playtest sessions" on public.playtest_sessions;
create policy "public can insert playtest sessions" on public.playtest_sessions
for insert to anon
with check (
  length(session_id) between 8 and 128
  and case_id in ('case01', 'case02', 'case03', 'case04', 'case05', 'final', 'season-final')
  and jsonb_typeof(summary) = 'object'
);
drop policy if exists "allow anonymous playtest feedback inserts" on public.playtest_feedback;
drop policy if exists "public can insert playtest feedback" on public.playtest_feedback;
create policy "public can insert playtest feedback" on public.playtest_feedback
for insert to anon
with check (
  length(session_id) between 8 and 128
  and (case_id is null or case_id in ('case01', 'case02', 'case03', 'case04', 'case05', 'final'))
);
drop policy if exists "public can insert app error logs" on public.app_error_logs;
create policy "public can insert app error logs" on public.app_error_logs
for insert to anon
with check (
  (session_id is null or length(session_id) between 8 and 128)
  and (current_case is null or current_case in ('unknown', 'case01', 'case02', 'case03', 'case04', 'case05', 'final'))
);

create table if not exists public.telemetry_rate_limits (
  actor_key text primary key,
  window_started_at timestamptz not null default now(),
  request_count integer not null default 0
);
alter table public.telemetry_rate_limits enable row level security;
revoke all on public.telemetry_rate_limits from anon;
revoke all on public.telemetry_rate_limits from authenticated;

create or replace function public.validate_telemetry_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  headers_text text;
  headers jsonb := '{}'::jsonb;
  actor_key text;
  request_count integer;
  window_started_at timestamptz;
  payload jsonb := to_jsonb(new);
  session_id_value text := payload->>'session_id';
  case_id_value text := payload->>'case_id';
  summary_value jsonb := coalesce(payload->'summary', '{}'::jsonb);
  score_text text := summary_value->>'burstScore';
begin
  if session_id_value is null or length(session_id_value) not between 8 and 128 then
    raise exception 'invalid telemetry session id';
  end if;

  -- Retries from a browser queue must not create a second record for one run/case.
  if TG_TABLE_NAME = 'playtest_sessions'
    and nullif(payload->>'run_id', '') is not null
    and exists (
      select 1 from public.playtest_sessions
      where run_id = payload->>'run_id'
        and case_id = payload->>'case_id'
    ) then
    return null;
  end if;

  headers_text := current_setting('request.headers', true);
  begin
    if headers_text is not null and headers_text <> '' then
      headers := headers_text::jsonb;
    end if;
  exception when others then
    headers := '{}'::jsonb;
  end;
  actor_key := left(coalesce(nullif(headers->>'x-forwarded-for', ''), session_id_value), 200);

  insert into public.telemetry_rate_limits (actor_key, window_started_at, request_count)
  values (actor_key, now(), 1)
  on conflict (actor_key) do update
  set request_count = case
    when now() - telemetry_rate_limits.window_started_at >= interval '1 hour' then 1
    else telemetry_rate_limits.request_count + 1
  end,
  window_started_at = case
    when now() - telemetry_rate_limits.window_started_at >= interval '1 hour' then now()
    else telemetry_rate_limits.window_started_at
  end
  returning request_count, window_started_at into request_count, window_started_at;

  if request_count > 120 then
    raise exception 'telemetry rate limit exceeded';
  end if;

  if TG_TABLE_NAME = 'playtest_sessions' then
    if case_id_value not in ('case01', 'case02', 'case03', 'case04', 'case05', 'final', 'season-final')
      or jsonb_typeof(summary_value) <> 'object'
      or jsonb_typeof(payload->'decision_log') <> 'array'
      or jsonb_array_length(payload->'decision_log') > 100 then
      raise exception 'invalid playtest session payload';
    end if;
    if case_id_value = 'season-final'
      and (summary_value->>'seasonComplete') <> 'true'
      and (summary_value->>'seasonComplete') <> '1' then
      raise exception 'season ranking requires a completed summary';
    end if;
    if case_id_value = 'season-final'
      and (score_text is null or score_text !~ '^[0-9]+([.][0-9]+)?$' or score_text::numeric not between 0 and 100) then
      raise exception 'invalid season ranking score';
    end if;
    if case_id_value = 'season-final'
      and summary_value->>'rank' not in ('S', 'A', 'B', 'C') then
      raise exception 'invalid season ranking rank';
    end if;
    if case_id_value = 'season-final'
      and (summary_value->>'averageResponseTime' is not null)
      and (summary_value->>'averageResponseTime') !~ '^[0-9]+([.][0-9]+)?$' then
      raise exception 'invalid season response time';
    end if;
    if case_id_value = 'season-final'
      and jsonb_array_length(payload->'decision_log') < 1 then
      raise exception 'season ranking requires decisions';
    end if;
  elsif TG_TABLE_NAME = 'playtest_feedback' then
    if payload->>'case_id' is not null and payload->>'case_id' not in ('case01', 'case02', 'case03', 'case04', 'case05', 'final') then
      raise exception 'invalid feedback case';
    end if;
  elsif TG_TABLE_NAME = 'app_error_logs' then
    if payload->>'current_case' is not null and payload->>'current_case' not in ('unknown', 'case01', 'case02', 'case03', 'case04', 'case05', 'final') then
      raise exception 'invalid error log case';
    end if;
  end if;

  return new;
end;
$$;

revoke execute on function public.validate_telemetry_insert() from public, anon, authenticated;

drop trigger if exists validate_playtest_session_insert on public.playtest_sessions;
create trigger validate_playtest_session_insert
before insert on public.playtest_sessions
for each row execute function public.validate_telemetry_insert();
drop trigger if exists validate_playtest_feedback_insert on public.playtest_feedback;
create trigger validate_playtest_feedback_insert
before insert on public.playtest_feedback
for each row execute function public.validate_telemetry_insert();
drop trigger if exists validate_app_error_log_insert on public.app_error_logs;
create trigger validate_app_error_log_insert
before insert on public.app_error_logs
for each row execute function public.validate_telemetry_insert();

-- Expose only completed-season ranking fields. Raw session rows contain the
-- decision log and must remain insert-only for anonymous clients.
revoke select on public.playtest_sessions from anon;
drop view if exists public.public_rankings;
create view public.public_rankings
with (security_invoker = true)
as
select
  run_id,
  session_code,
  player_name,
  case_id,
  case_title,
  completed_at,
  summary
from public.playtest_sessions
where case_id = 'season-final'
  and summary->>'seasonComplete' = 'true'
  and summary->>'burstScore' ~ '^[0-9]+([.][0-9]+)?$'
  and (summary->>'burstScore')::numeric between 0 and 100;
grant select on public.public_rankings to anon;

-- Healthcheck-only view for insert-only telemetry tables. This lets the debug
-- panel verify that the REST schema was deployed without exposing raw feedback
-- or error log rows to anonymous clients.
drop view if exists public.telemetry_health;
create view public.telemetry_health
with (security_invoker = true)
as
select 'playtest_feedback'::text as table_name
union all
select 'app_error_logs'::text as table_name;
grant select on public.telemetry_health to anon;
