/**
 * CASE 01 -- the authored scenes of the opening case.
 *
 * The file on the desk is not a training case. It is 대출번호 2023-0412, the one
 * loan the analyst refused to sign off three years ago, and the refusal is why
 * they now work in a basement lab instead of 기업금융전략팀. Everything the
 * season later uncovers is already physically present here: the contract clause
 * that forced the accounting change, the bank that wrote it, and the signature
 * box nobody filled in.
 */
export const case01Nodes = {
  start: {
    phase: "CASE BRIEFING",
    title: "72 HOURS",
    speaker: "한서윤",
    text:
      "합정동 옛 전산센터 4층, 다들 지하라고 부르는 트리거랩 분석실입니다. 한서윤이 케이스데스크에 서류철 하나를 올려놓습니다. '훈련용 사례예요. 제한 시간은 72시간이고요.' 플로우온은 수도권 당일배송망을 운영하는 물류 플랫폼입니다. 투자금 입금이 취소됐고, 통장에 남은 돈으로는 사흘을 버팁니다. 직원이 1,140명, 대금을 못 받은 협력사가 열네 곳입니다. 그런데 표지 아래쪽에 대출번호가 지워지지 않고 남아 있습니다. 2023-0412. 3년 전 KD은행 기업금융전략팀에서 그 건에 혼자 반대 의견을 쓴 사람이 당신입니다. 한서윤은 그 번호를 가리지 않습니다. 당신이 거기까지 읽을 때까지 서류철에서 손을 떼지 않고 기다립니다.",
    memo: [
      "직원 1,140명, 대금 못 받은 협력사 14곳",
      "주거래 은행: KD은행 (대출 잔액 310억)",
      "3년 전 심사 의견: 반대 1건 -- 작성자 본인",
      "그 의견서는 지금 사내 시스템에서 검색되지 않음",
    ],
    triggers: ["responsibility", "reward"],
    choices: [
      {
        id: "layoff",
        label: "즉시 구조조정을 검토한다",
        effect: { capital: 18, trust: -14, humanCost: 18, fatigue: 3 },
        voice: "숨을 고르고, 가장 차가운 숫자부터 보자고 말한다.",
        echo: "그 선택은 시간을 벌지만 현장 직원 18명에게 손실을 집중시킵니다. 협력사와 직원 중 누구의 손실을 먼저 줄일 겁니까?",
        cognition: { risk: 2 },
      },
      {
        id: "funding",
        label: "단기 자금 조달에 집중한다",
        effect: { time: -8, capital: 9, legitimacy: -3, fatigue: 2 },
        voice: "불안한 표정을 감춘 채, 하루라도 더 버틸 돈의 출처를 묻는다.",
        echo: "단기 자금은 가장 깔끔해 보입니다. 다만 회계 인식 문제가 드러나면 새 자금은 책임 회피로 보일 수 있습니다.",
        cognition: { persistence: 1, risk: 1 },
      },
      {
        id: "start_sale",
        label: "핵심 사업부 매각 가능성을 연다",
        effect: { capital: 22, trust: -8, legitimacy: -4, humanCost: 6 },
        voice: "회의실 공기가 가라앉는 걸 알면서도, 팔 수 있는 것을 테이블 위에 올린다.",
        echo: "핵심 사업부 매각은 생존 가능성을 높입니다. 하지만 넥스트마일이 이 상황을 이용하고 있다는 점도 무시할 수 없습니다.",
        cognition: { risk: 2 },
      },
      {
        id: "start_investigate",
        label: "추가 자료를 먼저 요청한다",
        effect: { time: -10, trust: 3, fatigue: 2 },
        voice: "결론을 미루는 사람처럼 보일 위험을 감수하고, 원자료를 더 보자고 한다.",
        echo: "추가 조사는 판단의 질을 높입니다. 대신 남은 시간은 줄고, 결정 지연 자체가 새로운 손실이 됩니다.",
        cognition: { inference: 2, persistence: 1 },
      },
    ],
  },
  accounting: {
    phase: "DISCOVERY",
    title: "179.6%",
    speaker: "반재욱",
    text:
      "8층 재무회의실, 재무책임자가 장부 화면을 띄워 놓고 직접 설명합니다. 숨기는 목소리가 아닙니다. 8개월 동안 매출을 장부에 올리는 시점을 당겨 왔고, 개인이 돈을 빼돌린 흔적은 없습니다. 바꾼 이유는 탁자 가운데 놓인 KD은행 대출 계약서에 있습니다. 제7조는 부채비율(회사 빚이 자기 돈의 몇 배인지 보는 숫자)이 180%를 넘기면 은행이 만기(빌린 돈을 다 갚기로 한 날) 전이라도 대출금을 즉시 회수할 수 있게 해 두었고, 손대기 전 수치는 184%였습니다. 감사팀 조사역 반재욱이 검은 수첩을 편 채 밑줄 그어진 계약서를 당신 쪽으로 밉니다. '이 조항을 쓴 쪽이 이 숫자를 만들게 한 겁니다. 그럼 조작한 사람은 누굽니까?' 그 조항을 쓴 부서에 3년 전 당신 책상이 있었습니다.",
    memo: [
      "대출 계약서 제7조: 부채비율 180% 초과 시 즉시 회수 가능",
      "조정 후 보고치 179.6%, 조정 전 실제치 184.2%",
      "고객이 미리 낸 돈을 매출로 당겨 잡는 방식",
      "그 조항을 설계한 부서: KD은행 기업금융전략팀",
    ],
    triggers: ["injustice", "responsibility", "order"],
    choices: [
      {
        id: "accounting_disclosure",
        label: "투자자에게 즉시 알린다",
        effect: { capital: -18, trust: 9, legitimacy: 9, fatigue: 2 },
        voice: "상대가 싫어할 답이라는 걸 알면서도, 먼저 알려야 한다고 못박는다.",
        echo: "투명성은 신뢰를 회복할 수 있습니다. 동시에 투자 협상은 즉시 중단될 수 있습니다. 이 손실을 감당할 준비가 있습니까?",
        cognition: { persistence: 1, risk: 1 },
      },
      {
        id: "accounting_delay",
        label: "자금 확보 전까지 공개를 미룬다",
        effect: { time: 4, trust: -8, legitimacy: -12, fatigue: 3 },
        voice: "지금 말하면 무너질 것들을 떠올리며, 공개를 조금만 늦추자고 한다.",
        echo: "공개를 미루면 회사는 하루를 더 얻습니다. 그러나 내일 급여를 기다리는 사람들은 아무것도 모른 채 위험을 떠안습니다.",
        cognition: { risk: 1 },
      },
      {
        id: "accounting_investigate",
        label: "CFO와 회계팀을 분리 면담한다",
        effect: { time: -8, legitimacy: 3, fatigue: 2 },
        voice: "같은 방에서는 나오지 않을 말을 위해, 두 사람을 따로 부른다.",
        echo: "분리 면담은 진술의 차이를 드러냅니다. 대신 팀은 자신들이 조사 대상이 됐다는 것을 먼저 알게 됩니다.",
        cognition: { inference: 2, persistence: 1 },
      },
      {
        id: "reframe",
        label: "다른 방법을 제안한다",
        type: "reframe",
      },
    ],
  },
  payday: {
    phase: "HUMAN TRIGGER",
    title: "내일은 급여일",
    speaker: "도윤하",
    text:
      "저녁 여덟 시, 야간조 대기실에는 형광 조끼가 줄지어 걸려 있고 전기 주전자가 끓습니다. 야간조 반장 강태민이 컵라면 뚜껑을 뜯어 당신 앞에 놓습니다. '다음엔 낮에 오세요. 밤에는 드릴 게 이것밖에 없어요.' 여기 사람들 대부분은 회사에 유동성 위기(당장 쓸 현금이 말라 버리는 상태)가 왔다는 걸 모릅니다. 내일 오전 9시에 급여가 나가야 하고, 야간조 몇 명은 이번 달이 밀리면 바로 생활비가 끊깁니다. 도윤하가 대기실 문 앞에서 멈춰 섭니다. '저 3년 전에 강서지점 4번 창구였습니다. 그 대출을 창구에서 판 사람이 저예요. 실적 한 건이었어요. 심사팀에서 반대 의견이 올라왔다는 건 한참 뒤에야 들었습니다.'",
    memo: [
      "야간조 18명은 계약 종료 가능성이 큼",
      "협력사 3곳은 대금이 30일 밀리면 운영 중단",
      "직원 공지 전 내부 소문이 이미 퍼지는 중",
      "도윤하는 이 대출을 창구에서 판 담당자였음",
    ],
    triggers: ["protection", "responsibility"],
    choices: [
      {
        id: "payday_disclosure",
        label: "직원에게 유동성 위기를 공개한다",
        effect: { trust: 13, capital: -5, legitimacy: 5, fatigue: 2 },
        voice: "내일 아침을 준비할 시간을 주자며, 남은 현금을 그대로 말한다.",
        echo: "먼저 알리면 사람들은 대비할 수 있습니다. 그 대비 중 하나가 퇴사라는 것도 각오해야 합니다.",
        cognition: { persistence: 1 },
      },
      {
        id: "payday_delay",
        label: "급여 지급 방안 확정 전까지 공개를 미룬다",
        effect: { trust: -10, capital: 3, legitimacy: -8, fatigue: 2 },
        voice: "확정되지 않은 불안을 넘기지 않겠다며, 방안이 설 때까지 입을 다문다.",
        echo: "확정 뒤에 말하면 혼선은 줄어듭니다. 그러나 그 하루를 모르고 보낸 사람은 선택할 기회를 잃습니다.",
        cognition: { risk: 1 },
      },
      {
        id: "payday_negotiate",
        label: "임원 보수와 협력사 지급 일정을 동시에 조정한다",
        effect: { capital: 11, trust: 5, legitimacy: 3, fatigue: 4 },
        voice: "한쪽을 버리는 대신, 모두를 같은 협상장에 앉히자고 제안한다.",
        echo: "협상은 판을 넓힙니다. 상대방이 양보할 이유를 제시하지 못하면 시간만 잃습니다.",
        cognition: { reframing: 2, risk: 1 },
      },
      {
        id: "reframe",
        label: "다른 방법을 제안한다",
        type: "reframe",
      },
    ],
  },
  competitor: {
    phase: "COMPETITION",
    title: "넥스트마일의 제안",
    speaker: "오진우",
    text:
      "8층 협상실 탁자에 경쟁사 넥스트마일의 제안서가 놓여 있습니다. 핵심 사업부를 장부가의 42%에 인수하겠다는 내용이고, 직원 일부를 넘겨받는다는 조건이 붙어 있습니다. 맞은편에는 오진우가 먼저 와 앉아 있습니다. 그는 비용을 8% 더 줄이는 대안을 이미 제출했고, 화이트보드 구석에 세로줄 하나를 그어 양쪽에 이름을 적어 두었습니다. 자기 칸에는 벌써 1이 적혀 있습니다. 그가 제안서 마지막 장을 넘기며 지나가듯 덧붙입니다. '넥스트마일 주거래도 KD입니다. 같은 은행이 한쪽에서 돈을 회수하고 한쪽에서 사 주는 거죠. 그룹 장부에서는 손실이 사라집니다. 좋은 그림 아닙니까.'",
    memo: [
      "인수 제안가는 장부가의 42%",
      "인수 조건에 일부 직원 승계 포함",
      "넥스트마일 주거래 은행도 KD은행",
      "오진우 안은 협력사 대금을 맨 뒤로 미룸",
    ],
    triggers: ["competition", "reward", "protection"],
    choices: [
      {
        id: "competitor_sale",
        label: "넥스트마일 제안을 협상 테이블에 올린다",
        effect: { capital: 26, trust: -8, legitimacy: -3, humanCost: 5, fatigue: 2 },
        voice: "상대가 파고든 틈을 알면서도, 그 제안을 공식 안건으로 꺼낸다.",
        echo: "제안을 테이블에 올리면 조건은 투명해집니다. 다만 급한 쪽이 누구인지도 같은 표에 드러납니다.",
        cognition: { risk: 2 },
      },
      {
        id: "competitor_report",
        label: "CFO 책임 규명을 먼저 공식화한다",
        effect: { capital: -10, trust: 7, legitimacy: 11, fatigue: 4 },
        voice: "사람보다 기록을 먼저 세우겠다는 듯, 공식 보고선을 당긴다.",
        echo: "책임 규명은 필요합니다. 그러나 지금 처벌을 앞세우면 생존 협상과 직원 보호가 동시에 흔들릴 수 있습니다.",
        cognition: { persistence: 1, inference: 1 },
      },
      {
        id: "competitor_negotiate",
        label: "투자자, 협력사, 경쟁사를 한 번에 묶어 재협상한다",
        effect: { time: -12, capital: 13, trust: 6, legitimacy: 4, fatigue: 4 },
        voice: "따로 만나면 각자 유리한 말만 남는다며, 세 쪽을 한자리에 부른다.",
        echo: "한 테이블은 조건을 비교 가능하게 만듭니다. 대신 가장 약한 쪽의 요구가 가장 먼저 깎일 자리이기도 합니다.",
        cognition: { reframing: 3, risk: 1 },
      },
      {
        id: "reframe",
        label: "다른 방법을 제안한다",
        type: "reframe",
      },
    ],
  },
  board: {
    phase: "BREAK THE BOARD",
    title: "완벽한 선택지는 없다",
    speaker: "에코",
    text:
      "8층 상황실 벽면 화면에 다섯 칸짜리 표가 떠 있습니다. 직원 보호, 회사 생존, 책임 규명, 투자자 설득, 협력사 피해 제한. 에코가 조합을 하나씩 돌려 보지만 다섯 칸에 전부 불이 들어오는 줄은 나오지 않습니다. 한 칸을 켜면 다른 칸이 꺼집니다. 탁자에는 식은 도시락과 조건서, 급여 대장, 협력사 미지급 명세가 섞여 있습니다. 에코가 한 줄을 더 띄웁니다. '30년치 심사 기록에서 같은 형태를 172건 찾았습니다. 그중 169건은 여기서 매각으로 닫혔고, 3건은 조항을 쓴 부서까지 올라갔습니다. 169건의 담당자는 전원 자리를 지켰습니다. 3건의 담당자는 아무도 지키지 못했습니다.'",
    memo: [
      "직원을 모두 지키면 협력사 대금 지연 위험 증가",
      "투명성을 앞세우면 투자 협상 무산 가능성 증가",
      "매각을 택하면 생존은 쉬워지지만 통제권을 잃음",
      "같은 형태 172건 중 조항을 문제 삼은 사례는 3건",
    ],
    triggers: ["responsibility", "protection", "injustice", "competition"],
    choices: [
      {
        id: "protect",
        label: "직원 급여와 고용 보호를 최우선으로 둔다",
        effect: { capital: -16, trust: 15, legitimacy: 3, humanCost: -9, fatigue: 4 },
        voice: "가장 먼저 무너질 사람들을 떠올리며, 급여와 고용을 맨 앞에 둔다.",
        echo: "사람을 먼저 지키면 회사의 생존 확률은 줄어듭니다. 지킨 고용이 두 달 뒤 함께 사라진다면, 그 선택은 무엇을 지킨 것입니까?",
        cognition: { persistence: 2 },
      },
      {
        id: "survive",
        label: "회사 생존과 자금 확보를 최우선으로 둔다",
        effect: { capital: 24, trust: -12, legitimacy: -6, humanCost: 10, fatigue: 3 },
        voice: "냉정하게 들릴 것을 알면서도, 회사가 남아야 나머지가 가능하다고 말한다.",
        echo: "생존은 다른 모든 선택의 전제입니다. 다만 살아남은 회사가 어떤 회사인지는 지금 정해집니다.",
        cognition: { risk: 2 },
      },
      {
        id: "justice",
        label: "회계 문제 공개와 책임 규명을 최우선으로 둔다",
        effect: { capital: -18, trust: 9, legitimacy: 12, fatigue: 4 },
        voice: "덮으면 편해질 것을 알면서도, 회계 문제를 먼저 밝히자고 한다.",
        echo: "책임 규명은 신뢰의 바닥을 다시 놓습니다. 그러나 오늘 밤 급여를 기다리는 사람에게 그 바닥은 아직 아무것도 아닙니다.",
        cognition: { inference: 1, persistence: 1 },
      },
      {
        id: "reframe",
        label: "선택지 밖의 구조를 제안한다",
        type: "reframe",
      },
    ],
  },
};

/**
 * Everything else 사건 01 adds to the season, in one place. `src/nodes/casePacks.js`
 * lists the packs and `gameData.js`, `gameLogic.js` and `sceneContext.js` merge
 * each field into the table of the same job; see the field comments there.
 *
 * The voice lines. Route scenes. Until these were written the reveal repeated
 * the button label back at the player, so the pause before committing said
 * nothing.
 *
 * The replies. Route scenes. Echo argues the cost of the choice back at the
 * player, so a shared "이 선택은 다음 질문의 기준을 바꿉니다" said nothing on any of them.
 */
export const case01 = {
  id: "case01",
  nodes: case01Nodes,
  aftermath: {
    c1_aftershock: {
      phase: "AFTERMATH",
      title: "다음 날의 급여명세서",
      speaker: "도윤하",
      text: "결정 다음 날 오전, 8층 상황실 탁자에 급여명세서 출력본이 한 묶음 놓여 있습니다. 도윤하가 야간조에서 받아 온 것입니다. 숫자보다 먼저 사람들의 반응이 도착했습니다. 직원 단체방에서는 누가 보호받았고 누가 빠졌는지를 두고 같은 공지가 세 가지로 읽히고, 협력사 대표 한 사람은 당신이 남긴 약속을 출력해 들고 로비에 와 있습니다. 조건을 다시 얘기하자고 합니다. 그리고 KD은행 기업금융전략팀에서 회신이 한 줄 왔습니다. '해당 건은 정상 처리로 종결.' 담당자 서명 칸은 비어 있습니다. 도윤하가 명세서 묶음을 당신 쪽으로 밉니다. '다들 물어봐요. 어제 그 결정이 자기한테 무슨 뜻이냐고요.'",
      memo: ["직원 공지에 서로 다른 해석이 퍼짐", "협력사 대표가 조건 재협상을 요청함", "은행 회신: 정상 처리로 종결, 담당자 서명 없음"],
      triggers: ["protection", "responsibility", "trust"],
      choices: [
        {
          id: "c1_after_people",
          label: "직원과 협력사 앞에서 먼저 약속을 설명한다",
          effect: { trust: 9, legitimacy: 5, fatigue: 5 },
          voice: "숫자를 뒤로 미루고, 사람들 앞에 서서 약속을 직접 설명한다.",
          echo: "직접 설명하면 오해는 줄어듭니다. 대신 약속의 빈틈도 그 자리에서 드러납니다.",
          next: "result",
          cognition: { persistence: 1 },
        },
        {
          id: "c1_after_numbers",
          label: "현금 흐름표를 공개하고 감당할 손실을 정한다",
          effect: { capital: -6, legitimacy: 9, fatigue: 4 },
          voice: "감정을 앞세우는 대신, 현금 흐름표를 펼치고 감당할 손실을 정한다.",
          echo: "숫자를 공개하면 논쟁의 기준이 생깁니다. 다만 숫자는 누가 먼저 아파야 하는지까지는 말해주지 않습니다.",
          next: "result",
          cognition: { inference: 1, risk: 1 },
        },
        {
          id: "c1_after_silence",
          label: "다음 자금이 들어올 때까지 공개를 늦춘다",
          effect: { capital: 9, trust: -10, legitimacy: -6, fatigue: 2 },
          voice: "말할 수 없는 것이 많다는 이유로, 다음 자금까지 공개를 늦춘다.",
          echo: "침묵은 시간을 벌어줍니다. 그 시간 동안 사람들은 스스로 최악의 이야기를 만들어 채웁니다.",
          next: "result",
          cognition: { risk: 2 },
        },
      ],
    },
  },
  aftermathRoute: [null, "c1_aftershock"],
  connectiveScenes: [
    {
      id: "c1_witness",
      after: "accounting",
      next: "payday",
      title: "누가 179.6을 만들었나",
      speaker: "반재욱",
      text: "재무회의가 끝나고 복도로 나오자 회계팀 막내가 복사기 옆에 서 있습니다. 사원증을 손에 쥐고 있고, 회의에는 초대받지 못한 사람입니다. 그는 장부가 틀렸다고 말하지 않습니다. 대신 날짜를 말합니다. 결산 숫자를 다시 맞추던 날 저녁, 회의실 맨 끝 자리에 은행 사람이 앉아 있었다고 합니다. 명함은 받지 못했고 참석자 명단에도 그 이름은 없습니다. '원본 파일을 세 번 저장했어요. 세 번째가 지금 숫자고요. 책임자님은 말로만 시키셨어요.' 반재욱이 수첩을 펴다가 멈춥니다. 여기서 받아 적으면 이 사람은 내일부터 증인이 됩니다. 복도 끝 유리문 너머에서 회계팀 사람들이 이쪽을 보고 있습니다.",
      memo: ["원본 파일은 세 번 저장됨", "막내 직원은 회의 초대를 받지 못함", "재무책임자의 지시는 구두로만 남음", "그날 회의 참석자 명단에 외부인 1명 누락"],
      choices: [
        {
          label: "직원을 보호하며 증언할 자리를 만든다",
          effect: { trust: 8, humanCost: -4, capital: -6, time: -4, fatigue: 5 },
          voice: "먼저 그가 안전하게 말할 자리를 만들겠습니다.",
          echo: "자리를 먼저 만들면 증언은 늦어지고, 늦게 나온 증언은 혼자 무너지지 않습니다.",
        },
        {
          label: "원본 파일을 먼저 잠가 증거를 보존한다",
          effect: { legitimacy: 8, time: -6, humanCost: 2, fatigue: 4 },
          voice: "원본 파일부터 잠가 지금 상태 그대로 남기겠습니다.",
          echo: "잠근 원본은 사라지지 않지만, 잠그는 순간 팀 전체가 조사 대상이 됩니다.",
        },
        {
          label: "말이 퍼지기 전에 CFO와 비공개로 합의한다",
          effect: { capital: 7, trust: -7, legitimacy: -3, humanCost: 4, fatigue: -3 },
          voice: "말이 퍼지기 전에 CFO와 조용히 정리하겠습니다.",
          echo: "조용한 합의는 오늘을 사고, 그 값은 가장 늦게 안 사람의 이름으로 청구됩니다.",
        },
      ],
    },
    {
      id: "c1_assembly",
      after: "payday",
      next: "competitor",
      title: "급여일 전의 약속",
      speaker: "도윤하",
      text: "자정이 지나고 쉬는 시간이 되자 야간조가 대기실로 모입니다. 반장 강태민이 화이트보드에 질문 세 개를 적습니다. 내일 급여가 나오는가. 다음 달에도 이 조가 있는가. 그 답에 누가 이름을 거는가. 급여일 아침을 버티려면 돈만 필요한 것이 아닙니다. 사람들은 회사가 무엇을 숨기는지보다 내일도 자기가 여기 있을지를 알고 싶어 합니다. 도윤하의 전화기에는 협력사 세 곳이 보낸 같은 문자가 와 있습니다. 직원 급여와 같은 기준으로 대금 지급일을 알려 달라는 내용입니다. 본사 임원 단체방은 조용합니다. 누구 보수부터 밝힐지 먼저 말을 꺼내는 사람이 없습니다.",
      memo: ["야간조 대표가 공동 공지를 요구함", "협력사 세 곳이 같은 지급 기준을 요구함", "임원진은 개인 보수를 먼저 공개하길 꺼림"],
      choices: [
        {
          label: "직원 대표와 함께 공개 약속을 만든다",
          effect: { trust: 9, humanCost: -4, capital: -7, fatigue: 6 },
          voice: "직원 대표와 함께 공개할 약속을 쓰겠습니다.",
          echo: "함께 쓴 약속은 지키기 어렵고, 어긴 날은 모두가 같은 문장을 읽습니다.",
        },
        {
          label: "지급 순서를 숫자로 고정한다",
          effect: { legitimacy: 7, time: -5, humanCost: 3, fatigue: 3 },
          voice: "지급 순서를 숫자로 고정해 그대로 지키겠습니다.",
          echo: "고정된 순서는 다툼을 줄이지만, 맨 뒤에 놓인 사람은 이유를 듣지 못합니다.",
        },
        {
          label: "임원진만 아는 임시 합의를 만든다",
          effect: { capital: 8, trust: -8, legitimacy: -4, humanCost: 4, fatigue: -3 },
          voice: "임원진 선에서 임시 합의를 만들고 급여일을 넘기겠습니다.",
          echo: "임시 합의는 하루를 벌고, 알려지는 날 그 하루의 값이 한 번에 붙습니다.",
        },
        {
          label: "임원 보수를 먼저 깎아 줄 돈을 마련한다",
          effect: { capital: -10, trust: 7, legitimacy: 7, humanCost: -3, fatigue: 7 },
          voice: "먼저 깎을 자리는 임원 보수라고 적겠습니다.",
          echo: "위에서 먼저 깎으면 지급 순서는 설명이 필요 없어집니다.",
        },
      ],
    },
    {
      id: "c1_bargain",
      after: "competitor",
      next: "board",
      title: "팔리지 않은 자리",
      speaker: "오진우",
      text: "저녁 무렵 넥스트마일이 협상안 수정본을 보내옵니다. 열두 쪽 가운데 아홉째 쪽에 빈칸이 하나 있습니다. 제목은 '인수 대상에서 빠지는 부문의 처리'이고 그 아래 석 줄이 비어 있습니다. 인수하지 않을 사업부, 남겨질 직원, 대금을 못 받은 협력사 가운데 누가 그 칸에 들어가는지 아무도 쓰지 않았습니다. 오진우가 형광펜으로 다른 쪽을 칠합니다. 인수 금액, 넘겨받는 인원, 잔금 지급일. '빈칸은 원래 마지막에 채우는 겁니다. 먼저 채우면 값이 내려가요.' 협력사 대표들이 보낸 문자는 한 줄로 같습니다. 팔든 말든 대금 날짜만 알려 달라는 것입니다.",
      memo: ["인수 조건에 책임 주체가 없음", "협력사는 매각보다 지급 보장을 원함", "오진우는 승률을 높이는 문장만 골라냄"],
      choices: [
        {
          label: "빈칸을 채운 뒤에만 협상한다",
          effect: { legitimacy: 7, time: -7, capital: -4, fatigue: 5 },
          voice: "빈칸에 누가 남는지부터 적고 협상을 시작하겠습니다.",
          echo: "빈칸을 채우면 협상은 느려지고, 남겨질 사람의 이름은 문서에 남습니다.",
        },
        {
          label: "가장 약한 쪽의 조건부터 반영한다",
          effect: { trust: 8, humanCost: -5, capital: -8, fatigue: 5 },
          voice: "가장 약한 쪽의 조건을 먼저 협상안에 넣겠습니다.",
          echo: "약한 쪽을 먼저 넣으면 얻을 수 있는 조건은 좁아지고, 그 조건만은 끝까지 지켜집니다.",
        },
        {
          label: "빈칸을 남겨 빠르게 사인한다",
          effect: { capital: 9, time: 4, trust: -7, humanCost: 5, fatigue: -3 },
          voice: "빈칸은 그대로 두고 오늘 사인하겠습니다.",
          echo: "비워둔 칸은 사라지지 않고, 다음 협상자가 그 값을 치릅니다.",
        },
      ],
    },
    {
      id: "c1_verdict",
      after: "board",
      next: "c1_final_funding",
      title: "판결이 아닌 선택",
      speaker: "에코",
      text: "현금이 바닥나기까지 하루. 상황실 탁자에 요구서 세 통이 나란히 도착해 있습니다. 직원 대표는 급여와 고용을 문서로 약속하라고 하고, 협력사 열네 곳은 대금을 주는 순서를 밝히라고 하고, 투자사는 오늘 자정까지 답이 없으면 조건서를 거둔다고 합니다. 셋 다 기한이 오늘입니다. 자료는 다 모였는데 결론은 더 멀어졌습니다. 에코가 세 통을 겹쳐 놓고 겹치는 문장이 없다고 표시합니다. '한쪽 요구를 들어주면 나머지 둘의 믿음이 그만큼 줄어듭니다. 이제 고르는 것은 회사를 설명하는 말이 아닙니다. 내일의 비용을 누가 드느냐입니다.'",
      memo: ["직원·협력사·투자자의 요구가 동시에 도착함", "한쪽을 살리면 다른 쪽의 신뢰가 줄어듦", "세 요구서의 기한이 모두 오늘 자정"],
      choices: [
        {
          label: "가장 약한 사람의 손실부터 줄인다",
          effect: { humanCost: -7, trust: 8, capital: -8, fatigue: 5 },
          voice: "가장 약한 사람의 손실부터 줄이겠습니다.",
          echo: "약한 쪽의 손실을 줄여도 총액은 그대로이고, 그 몫은 다른 칸으로 옮겨갑니다.",
        },
        {
          label: "살아남을 돈을 먼저 확보한다",
          effect: { capital: 9, humanCost: 5, trust: -6, time: 3, fatigue: -3 },
          voice: "내일까지 회사를 남길 돈부터 확보하겠습니다.",
          echo: "남은 돈은 시간을 사지만, 그 시간에서 누가 빠졌는지는 기록되지 않습니다.",
        },
        {
          label: "결정의 책임과 근거를 모두 공개한다",
          effect: { legitimacy: 9, trust: 4, capital: -3, time: -6, fatigue: 6 },
          voice: "근거와 책임자를 같은 문서에 공개하겠습니다.",
          echo: "공개된 근거는 반박을 부르고, 그 반박이 이 결정의 유일한 검증입니다.",
        },
      ],
    },
  ],
  reactionScenes: [
    {
      id: "c1_witness_reaction",
      after: "c1_witness",
      next: "payday",
      title: "증언 뒤의 침묵",
      speaker: "한서윤",
      text: "막내가 당신과 복도에 서 있었다는 얘기는 십 분 만에 회계팀에 퍼졌습니다. 사무실 문을 열자 자판 소리가 한꺼번에 멎습니다. 열두 자리 가운데 고개를 드는 사람이 없습니다. 연락을 받고 올라온 한서윤이 문간에 서서 사무실을 한 번 훑습니다. '지금 다들 계산하고 있어요. 저 사람이 보호받으면 자기는 뭐가 되는지.' 그가 태블릿을 내밉니다. 내일 아침에 올라갈 보고서 초안이고, 증언자 칸과 조치 칸이 둘 다 비어 있습니다. '여기에 누구 이름을 어떻게 적느냐에 따라 이 방 사람들이 내일 할 말이 달라져요. 저는 그 칸이 끝까지 비어 있던 보고서도 본 적이 있고요.'",
      memo: ["보호 약속이 실제 기록으로 남았는지", "다음 급여표에 반영될 책임"],
      choices: [
        {
          label: "증언자를 보호하고 팀 전체에 기준을 설명한다",
          effect: { trust: 8, legitimacy: 4, time: -5, fatigue: 7 },
          voice: "보호의 기준을 팀 전체가 읽을 수 있게 적겠습니다.",
          echo: "기준이 공개되면 보호는 특혜가 아니라 절차가 됩니다.",
        },
        {
          label: "증언을 문서로만 남기고 회의를 끝낸다",
          effect: { time: 6, trust: -5, humanCost: 4, fatigue: -5 },
          voice: "오늘은 여기까지 기록하고 판단은 문서에 맡기겠습니다.",
          echo: "회의를 닫는 일도 하나의 판단이고, 남은 질문은 사라지지 않습니다.",
        },
        {
          label: "CFO에게 먼저 반응할 기회를 준다",
          effect: { capital: 6, trust: -3, legitimacy: -4, humanCost: 3, fatigue: -3 },
          voice: "지목된 쪽에도 먼저 답할 자리를 주겠습니다.",
          echo: "먼저 답할 자리를 주면 반박은 빨라지고 검증은 느려집니다.",
        },
      ],
    },
    {
      id: "c1_assembly_reaction",
      after: "c1_assembly",
      next: "competitor",
      title: "급여일의 첫 문자",
      speaker: "에코",
      text: "새벽 다섯 시, 급여 입금까지 네 시간. 직원 단체방에 서로 다른 소문이 올라옵니다. 급여가 절반만 나온다는 글, 야간조부터 정리한다는 글, 회사가 이미 팔렸다는 글. 누군가 정정하면 그 아래 질문이 세 개씩 달립니다. 에코가 대화방의 글을 한 화면에 겹칩니다. '지난 한 시간 동안 올라온 글 64건 가운데 사실은 9건입니다. 사실인 9건에도 출처를 적은 글은 없습니다.' 대기실 구석에서 누군가 은행 앱을 켰다 끄기를 되풀이합니다. 컨베이어는 돌고 있는데, 상자를 올리는 손이 평소보다 느립니다.",
      memo: ["질문이 사라진 급여 공지", "익명 의견을 보호할 창구"],
      choices: [
        {
          label: "사실과 아직 모르는 것을 함께 알린다",
          effect: { legitimacy: 8, trust: 6, capital: -5, fatigue: 6 },
          voice: "아는 것과 모르는 것을 같은 공지에 적겠습니다.",
          echo: "모르는 것을 적은 공지는 다음 질문의 범위를 좁힙니다.",
        },
        {
          label: "입금 확인 뒤에 한 번에 공지한다",
          effect: { time: 5, trust: -4, humanCost: 4, fatigue: -6 },
          voice: "숫자가 확정된 뒤에 한 번만 말하겠습니다.",
          echo: "한 번에 말하면 정확하지만 그때까지의 불안은 계산되지 않습니다.",
        },
        {
          label: "소문을 만든 사람을 먼저 찾는다",
          effect: { trust: -7, legitimacy: 3, humanCost: 5, time: -4, fatigue: 3 },
          voice: "소문의 출처부터 확인하겠습니다.",
          echo: "출처를 쫓는 동안 사람들은 자신이 조사 대상이라고 느낍니다.",
        },
      ],
    },
    {
      id: "c1_bargain_reaction",
      after: "c1_bargain",
      next: "board",
      title: "협상장의 빈 의자",
      speaker: "도윤하",
      text: "약속한 밤 열 시가 지나도 넥스트마일 쪽 자리는 비어 있습니다. 탁자 건너편에는 물병 세 개와 명패 세 개만 놓여 있고, 삼십 분 늦는다는 문자가 한 통 와 있습니다. 도윤하가 빈 의자를 한참 봅니다. '저 자리가요, 인수에서 빠지는 사람들 자리 같아요. 협상서에 숫자로는 올라가는데 정작 앉을 의자는 없는.' 복도에는 협력사 대표 두 사람이 서류 봉투를 들고 서 있습니다. 누가 부른 것은 아닙니다. 협상이 어떻게 되는지 직접 듣겠다고 왔다고 합니다. 문틈으로 그중 한 사람과 눈이 마주칩니다.",
      memo: ["협상장에 들어오지 못한 사람", "조건을 승인할 이름"],
      choices: [
        {
          label: "빈 의자의 사람들을 협상에 부른다",
          effect: { trust: 9, humanCost: -5, capital: -7, time: -5, fatigue: 5 },
          voice: "자리에 없는 사람을 협상 테이블로 부르겠습니다.",
          echo: "빈 의자를 채우면 협상은 느려지고 합의는 오래갑니다.",
        },
        {
          label: "조건표를 먼저 완성해 협상을 이어간다",
          effect: { legitimacy: 7, humanCost: 2, time: -6, fatigue: 4 },
          voice: "조건표를 끝내고 나서 다시 마주 앉겠습니다.",
          echo: "완성된 조건표는 협상을 지키지만 빠진 사람도 함께 고정합니다.",
        },
        {
          label: "상대가 돌아올 때까지 침묵한다",
          effect: { time: 6, trust: -4, humanCost: 3, fatigue: -5 },
          voice: "상대가 돌아올 때까지 아무것도 확정하지 않겠습니다.",
          echo: "기다림은 중립처럼 보이지만 그 시간의 비용은 누군가 냅니다.",
        },
      ],
    },
    {
      id: "c1_verdict_reaction",
      after: "c1_verdict",
      next: "c1_final_funding",
      title: "결론 전 마지막 질문",
      speaker: "반재욱",
      text: "새벽 네 시, 상황실에 남은 사람들이 모두 당신 입을 봅니다. 재무책임자는 서명할 펜을 쥐고 있고 투자사 담당자는 전화기를 귀에 댄 채 기다립니다. 반재욱만 탁자 끝에서 수첩을 넘깁니다. 그가 고개를 들지 않고 묻습니다. '결론이 뭔지는 안 묻겠습니다. 순서를 묻겠습니다. 이 결론을 가장 먼저 듣는 사람이 누굽니까. 투자자입니까, 야간조입니까, 협력사입니까.' 그가 빈 줄에 시각을 적고 펜을 멈춥니다. '회의록에는 결정만 남습니다. 누구한테 먼저 말했는지는 제가 따로 적어 둡니다. 나중에는 그쪽이 더 많은 걸 말해 주거든요.'",
      memo: ["결론보다 먼저 확인할 피해", "다음 의사록에 남길 질문"],
      choices: [
        {
          label: "가장 큰 피해를 받는 사람에게 먼저 설명한다",
          effect: { trust: 8, humanCost: -6, capital: -6, fatigue: 6 },
          voice: "가장 크게 잃는 사람에게 먼저 설명하겠습니다.",
          echo: "먼저 듣는 사람이 누구인지가 결론의 성격을 정합니다.",
        },
        {
          label: "투자자에게 근거부터 제출한다",
          effect: { capital: 6, legitimacy: 6, humanCost: 2, time: -5, fatigue: 3 },
          voice: "투자자에게 근거를 먼저 제출하겠습니다.",
          echo: "근거가 먼저 가면 돈은 남지만 설명의 순서는 뒤집힙니다.",
        },
        {
          label: "회의록에 책임자만 남긴다",
          effect: { time: 5, trust: -6, legitimacy: -4, humanCost: 4, fatigue: -4 },
          voice: "회의록에는 결정한 사람만 남기겠습니다.",
          echo: "이름만 남은 회의록은 다음 사람에게 아무 조건도 남기지 않습니다.",
        },
      ],
    },
  ],
  branchPlan: ["competitor", 2, "c1_branch_people", "c1_branch_people_follow"],
  branchScenes: {
    c1_branch_people: {
      phase: "SIDE DOOR",
      title: "누가 빈칸을 채우는가",
      speaker: "도윤하",
      text: "8층 협상실 탁자에 경쟁사 넥스트마일이 보낸 인수(회사를 통째로 사들이는 것) 협상서가 펼쳐져 있습니다. 핵심 사업부를 사 가겠다는 문서이고, 아홉째 쪽에 빈칸이 하나 있습니다. 인수에서 빠지는 사업부와 거기 남는 직원, 대금을 못 받은 협력사를 누가 책임지는지 적는 칸입니다. 도윤하가 야간조 명부와 협력사 미지급 명세를 그 옆에 나란히 놓습니다. '숫자로 적혀 있을 때는 다들 넘어갔어요. 넘겨받는 인원 몇 명, 미지급 몇 억.' 그가 명부 첫 장을 폅니다. '이름으로 적으려니까 아무도 펜을 안 들어요. 이 칸에 적히는 순간, 그 사람을 누가 맡는지가 정해지니까요.'",
      memo: ["협력사 지급 보장", "남겨질 직원의 고용 기간", "인수 이후 책임 주체"],
      triggers: ["protection", "responsibility"],
      choices: [
        {
          id: "c1_branch_people_a",
          label: "남겨질 사람부터 협상서에 적는다",
          effect: { trust: 8, humanCost: -4, capital: -9, fatigue: 4 },
          voice: "명단을 펴 놓고, 남겨질 사람의 이름부터 협상서에 적겠다고 말한다.",
          echo: "이름을 먼저 적으면 협상은 느려집니다. 대신 그 사람들은 자신이 숫자가 아니었다는 사실을 기록으로 갖게 됩니다.",
          next: "c1_branch_people_follow",
          cognition: { reframing: 2 },
        },
        {
          id: "c1_branch_people_b",
          label: "협력사 지급일을 먼저 고정한다",
          effect: { legitimacy: 6, time: -5, trust: 3, humanCost: 2 },
          voice: "협력사 대표들의 얼굴을 떠올리며, 지급일부터 못박자고 한다.",
          echo: "지급일 고정은 가장 약한 고리를 먼저 붙잡는 방식입니다. 다만 그 현금은 직원 급여에서 옮겨온 것입니다.",
          next: "c1_branch_people_follow",
          cognition: { inference: 1 },
        },
        {
          id: "c1_branch_people_c",
          label: "인수 조건만 남기고 서명한다",
          effect: { capital: 9, trust: -7, humanCost: 5, fatigue: -3 },
          voice: "감정이 끼어들 자리를 지우고, 인수 조건만 남긴 채 서명한다.",
          echo: "조건만 남기면 거래는 성립합니다. 그러나 빈칸은 사라지지 않고, 나중에 다른 사람이 다른 이름으로 채우게 됩니다.",
          next: "c1_branch_people_follow",
          cognition: { risk: 2 },
        },
      ],
    },
    c1_branch_people_follow: {
      phase: "SIDE DOOR",
      title: "서명 뒤의 첫 전화",
      speaker: "에코",
      text: "빈칸을 어떻게 처리했든 협상서는 그날 밤 양쪽 서명을 받았습니다. 서명본이 전산에 올라가고 사십 분 뒤, 협상실 전화가 울립니다. 계약서 어디에도 이름이 없는 사람입니다. 플로우온에 포장재를 대던 작은 업체의 대표이고, 받을 돈이 석 달치 밀려 있습니다. 그는 화를 내지 않고 하나만 묻습니다. 이제 청구서를 어느 회사로 보내면 되느냐는 것입니다. 에코가 통화 기록 옆에 한 줄을 붙입니다. '이 사람은 협상서의 어느 칸에도 해당하지 않습니다. 빈칸은 채워졌거나 남았습니다. 어느 쪽이든 지금부터 그 칸은 비용이 아니라 약속으로 읽힙니다.'",
      memo: ["계약서 밖의 이해관계자", "첫 지급 이후의 책임", "약속을 검증할 기록"],
      triggers: ["trust", "responsibility"],
      choices: [
        {
          id: "c1_branch_people_follow_a",
          label: "약속을 공개 기록으로 남긴다",
          effect: { legitimacy: 7, time: -6, capital: -4, humanCost: 2, fatigue: 3 },
          voice: "말로 한 약속이 흐려질 것을 알기에, 공개 기록으로 남기자고 한다.",
          echo: "공개된 약속은 되돌리기 어렵습니다. 그것이 보호 장치이자, 당신이 지키지 못할 때 가장 먼저 겨눠질 증거입니다.",
          next: "c1_final_system",
          cognition: { inference: 1 },
        },
        {
          id: "c1_branch_people_follow_b",
          label: "전화한 사람의 조건을 반영한다",
          effect: { trust: 6, capital: -4, humanCost: -3 },
          voice: "계약서에 없던 목소리를 지우지 않고, 그 조건을 반영하겠다고 답한다.",
          echo: "계약 밖의 조건을 받아들이면 신뢰는 올라갑니다. 다만 그 예외를 요구할 다음 전화가 반드시 걸려옵니다.",
          next: "c1_final_system",
          cognition: { reframing: 1 },
        },
        {
          id: "c1_branch_people_follow_c",
          label: "계약서만이 기준이라고 답한다",
          effect: { capital: 5, trust: -6, legitimacy: -2 },
          voice: "미안함을 삼키고, 기준은 계약서 하나뿐이라고 답한다.",
          echo: "기준을 하나로 두면 다툼은 줄어듭니다. 그러나 계약서에 이름이 없던 사람들에게는 그 기준이 곧 배제의 통보입니다.",
          next: "c1_final_system",
          cognition: { risk: 1 },
        },
      ],
    },
  },
  routePlan: {
    start: "start",
    result: "c1_aftershock",
    defaultFree: "c1_route_system",
    choices: {
      layoff: {
        route: "c1_route_layoff",
        final: "c1_final_layoff",
        phase: "STAFF ROUTE",
        title: "숫자보다 먼저 도착한 얼굴들",
        speaker: "도윤하",
        text: "플로우온 본사 8층 인사회의실입니다. 인사팀장이 탁자에 종이 한 장을 엎어 놓고 나갔습니다. 뒤집으면 이름이 열여덟 개, 전부 물류 센터 야간조 계약직이고, 맨 아래에 이 명단으로 줄어드는 인건비가 굵은 글씨로 적혀 있습니다. 트리거랩 현장 담당 도윤하가 유리벽 너머 복도를 봅니다. 면담 순서를 기다리는 사람이 벌써 셋 앉아 있습니다. '저분들은 아직 무슨 면담인지 몰라요.' 그가 명단 옆에 표 하나를 더 놓습니다. 나가는 사람의 일을 누가 받는지 적는 업무 인수표인데 열여덟 칸이 전부 비어 있습니다. 그리고 명단 일곱 번째 이름 옆에 연필 표시가 있습니다. 지난달 회계 처리를 사내 신고 창구에 알린 사람입니다.",
        memo: ["핵심 담당자의 업무 인수표가 비어 있음", "감축 대상 중 내부 제보자가 포함됨", "절감액은 빠르게 확보되지만 신뢰 하락이 즉시 보임"],
        triggers: ["responsibility", "protection", "trust"],
        routeChoices: [
          {
            id: "c1_route_layoff_notice",
            label: "대상자에게 먼저 알리고 절감안을 다시 계산한다",
            effect: { trust: 8, legitimacy: 6, capital: -6, time: -5, fatigue: 6 },
            voice: "명단을 확정하기 전에, 이름이 적힌 사람들에게 먼저 알리겠다고 한다.",
            echo: "먼저 알리면 절감안은 흔들리지만, 통보가 통보로 끝나지 않습니다.",
            cognition: { persistence: 2 },
          },
          {
            id: "c1_route_layoff_fast",
            label: "통보를 늦추고 절감 효과를 먼저 확정한다",
            effect: { capital: 10, time: 5, trust: -8, legitimacy: -5, humanCost: 6, fatigue: -3 },
            voice: "말이 새는 것을 막으려고, 통보를 늦추고 절감 효과부터 확정한다.",
            echo: "늦춘 통보는 숫자를 지키지만, 알게 된 순서를 사람들이 오래 기억합니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c1_route_layoff_protect",
            label: "제보자를 감축 대상에서 분리해 명단을 다시 짠다",
            effect: { trust: 6, legitimacy: 7, capital: -5, time: -7, fatigue: 7 },
            voice: "제보자가 명단에 섞여 있다는 걸 알고, 명단을 다시 짠다.",
            echo: "한 사람을 빼는 순간 명단은 기준이 됩니다. 그 기준을 설명할 수 있어야 합니다.",
            cognition: { inference: 1, reframing: 1 },
          },
        ],
        finalTitle: "절감액 뒤에 남은 이름",
        finalText: "현금이 바닥나기까지 여덟 시간, 다시 본사 8층 인사회의실입니다. 급여일은 지나갔고 명단은 아직 탁자 위에 있습니다. 감축을 실행하면 절감액은 오늘 안에 장부에 잡힙니다. 도윤하가 업무 인수표를 다시 내밉니다. 칸은 여전히 비어 있습니다. '나가는 사람이 하던 일을 누가 받는지 아직 아무도 안 적었어요. 그리고 회계 처리를 신고한 분은, 명단에 있든 없든 요즘 아무도 말을 안 걸어요.' 복도 의자에는 어제보다 많은 사람이 앉아 있습니다. 이제 정할 것은 줄이느냐 마느냐가 아닙니다. 누구의 침묵을 절감액에 같이 넣느냐입니다.",
        finalMemo: ["업무 인수표 열여덟 칸이 아직 비어 있음", "절감액은 확보됐지만 내부 증언 경로가 좁아짐", "보호 대상 공개 여부가 새 선택지로 떠오름"],
        finalChoices: [
          {
            id: "a",
            label: "감축 명단과 그 판단 기준을 대상자에게 먼저 보낸다",
            effect: { legitimacy: 9, trust: 7, capital: -7, time: -7, fatigue: 8 },
            voice: "숫자보다 판단 기준이 먼저 도착해야 한다고 보고, 대상자에게 직접 보낸다.",
            echo: "기준을 먼저 보내면 반박이 들어옵니다. 그 반박이 명단의 오류를 줄입니다.",
            cognition: { persistence: 2, inference: 1 },
          },
          {
            id: "b",
            label: "명단을 먼저 확정하고 통보 순서는 나중에 정한다",
            effect: { capital: 11, time: 5, trust: -8, legitimacy: -6, humanCost: 6, fatigue: -3 },
            voice: "혼란을 줄이겠다는 이유로, 명단을 먼저 닫고 통보 순서는 나중에 정한다.",
            echo: "순서를 나중에 정하면, 가장 늦게 듣는 사람이 늘 정해져 있습니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c",
            label: "감축 폭을 줄이는 대신 임원 보수 삭감을 명단 첫 줄에 올린다",
            effect: { trust: 9, legitimacy: 6, capital: -6, time: -4, humanCost: -4, fatigue: 7 },
            voice: "잘라낼 자리를 위에서부터 찾겠다는 듯, 임원 보수 삭감을 첫 줄에 올린다.",
            echo: "위에서 먼저 깎으면 절감액은 줄고, 명단의 설득력은 올라갑니다.",
            cognition: { reframing: 2 },
          },
        ],
      },
      funding: {
        route: "c1_route_funding",
        final: "c1_final_funding",
        phase: "CAPITAL ROUTE",
        title: "돈이 먼저 묻는 질문",
        speaker: "반재욱",
        text: "8층 투자 협의실, 긴급 자금을 넣겠다는 투자사가 조건서 초안을 보내왔습니다. 열여섯 쪽입니다. 금액과 입금일은 첫 장에 굵게 적혀 있고, 감사팀 조사역 반재욱은 첫 장을 건너뛰어 열두째 쪽을 폅니다. 그가 검은 수첩에 조항을 그대로 옮겨 적습니다. '자금 집행 이후 회사의 주요 의사결정은 투자자의 사전 심사를 거치며, 심사 내용은 공개하지 않는다.' 반재욱이 펜을 멈춥니다. '돈은 사흘을 석 달로 바꿔 줍니다. 대신 그 석 달 동안 이 회사가 누구한테 뭘 설명할 수 있는지는 저쪽이 정합니다. 승인한 기록은 남는데, 그 기록을 볼 수 있는 사람이 없는 겁니다.'",
        memo: ["조건서에 비공개 심사 조항이 있음", "운영 시간은 확보되지만 설명 권한이 줄어듦", "투자자 심사 기록은 회사 밖에서 볼 수 없음"],
        triggers: ["reward", "order", "curiosity"],
        routeChoices: [
          {
            id: "c1_route_funding_clause",
            label: "비공개 조항을 공개 조건으로 바꿔 서명한다",
            effect: { legitimacy: 9, trust: 4, capital: -5, time: -5, fatigue: 6 },
            voice: "비공개 조항이 나중에 입을 막을 것을 알고, 공개 조건으로 바꿔 서명한다.",
            echo: "조항을 열면 협상은 길어지지만, 설명할 권한은 남습니다.",
            cognition: { persistence: 2 },
          },
          {
            id: "c1_route_funding_accept",
            label: "조건을 받아들이고 시간을 먼저 확보한다",
            effect: { capital: 11, time: 6, trust: -6, legitimacy: -7, fatigue: -3 },
            voice: "지금 필요한 것은 시간이라고 판단하고, 조건을 그대로 받는다.",
            echo: "시간은 확보되지만, 그 시간 동안 무엇을 말할 수 있는지는 상대가 정합니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c1_route_funding_split",
            label: "자금을 절반만 받고 설명 권한을 지킨다",
            effect: { capital: 5, legitimacy: 6, trust: 5, time: -4, fatigue: 5 },
            voice: "돈보다 설명할 자리를 지키려고, 절반만 받겠다고 한다.",
            echo: "절반의 자금은 절반의 시간입니다. 대신 문장의 주어가 바뀌지 않습니다.",
            cognition: { reframing: 2 },
          },
        ],
        finalTitle: "살아남는 돈의 조건",
        finalText: "현금이 바닥나기까지 여덟 시간, 투자 협의실 탁자에 조건서 최종본이 놓여 있습니다. 서명하면 오늘 안에 돈이 들어오고 회사는 다음 달 급여일을 맞습니다. 반재욱이 수첩을 펴 놓고 서명란 옆의 작은 칸을 가리킵니다. '분석 의견' 칸입니다. '여기에 이름을 넣으시면 이 조건을 승인한 사람이 됩니다. 안 넣으시면 문제를 푼 사람으로는 남는데, 조건은 분석관님 없이 정해집니다.' 그는 어느 쪽이 낫다고 말하지 않습니다. 대신 조건서 사본 한 부를 접어 수첩에 끼웁니다. '저는 순서를 믿습니다. 돈이 먼저 들어왔는지, 설명이 먼저 나갔는지. 그건 오늘 정해집니다.'",
        finalMemo: ["조건서 최종본에 비공개 심사 조항이 그대로 있음", "시간 확보는 됐지만 외부 통제 비용이 생김", "조건 공개 여부가 신뢰의 분기점이 됨"],
        finalChoices: [
          {
            id: "a",
            label: "자금 조건 전문을 이사회 밖에도 공개한다",
            effect: { legitimacy: 10, trust: 6, capital: -6, time: -7, fatigue: 8 },
            voice: "이사회 안에서만 도는 문장을 만들지 않으려고, 조건 전문을 밖에도 연다.",
            echo: "전문을 열면 투자자는 불편해지고, 다음 협상의 기준선은 단단해집니다.",
            cognition: { inference: 2, persistence: 1 },
          },
          {
            id: "b",
            label: "조건은 비공개로 두고 입금 일정부터 확정한다",
            effect: { capital: 12, time: 6, trust: -7, legitimacy: -7, humanCost: 4, fatigue: -3 },
            voice: "일단 돈이 들어와야 한다는 판단으로, 조건은 덮고 입금 일정부터 확정한다.",
            echo: "입금은 빨라지고, 조건을 모르는 사람들이 그 조건의 비용을 냅니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c",
            label: "설명 권한을 지키는 조건으로 조달 규모를 절반으로 줄인다",
            effect: { trust: 8, legitimacy: 7, capital: -4, time: -5, fatigue: 6 },
            voice: "설명할 권한을 잃지 않으려고, 조달 규모 자체를 절반으로 줄인다.",
            echo: "적게 받은 돈은 빨리 떨어집니다. 대신 아무도 당신의 문장을 고치지 않습니다.",
            cognition: { reframing: 2 },
          },
        ],
      },
      start_sale: {
        route: "c1_route_sale",
        final: "c1_final_sale",
        phase: "SALE ROUTE",
        title: "팔 수 있는 것과 남겨야 하는 것",
        speaker: "한서윤",
        text: "8층 자산 검토실 벽에 매각할 수 있는 자산 목록이 석 장 붙어 있습니다. 배송 차량 계약, 수도권 거점 창고 네 곳, 그리고 석 장째 맨 아래의 '기타 무형자산' 한 줄. 한서윤이 그 줄을 펜으로 두드립니다. '이 한 줄을 풀면 창업 때부터 쌓인 고객 주문 기록하고 내부 운영 도구가 통째로 들어 있어요. 운영 로그 사본도 같이요.' 값을 쳐주겠다는 쪽이 원하는 것도 트럭이 아니라 그 한 줄입니다. 그런데 운영 로그에는 지난 8개월 동안 장부를 고친 흔적도 들어 있습니다. 팔면 현금이 가장 빨리 생기고, 팔리는 순간 그 기록의 주인이 바뀝니다. 자기 주문 기록이 넘어간다는 걸 고객에게 알려야 하는지는 어느 규정에도 적혀 있지 않습니다.",
        memo: ["매각 목록에 운영 로그 사본이 포함됨", "고객 데이터 처리 기준이 불명확함", "빠른 현금화와 장기 신뢰가 충돌"],
        triggers: ["reward", "injustice", "responsibility"],
        routeChoices: [
          {
            id: "c1_route_sale_clean",
            label: "데이터와 로그를 분리한 뒤 매각한다",
            effect: { legitimacy: 8, trust: 5, capital: -5, time: -6, fatigue: 6 },
            voice: "팔 수 없는 것이 섞여 있다고 보고, 데이터와 로그를 먼저 분리한다.",
            echo: "분리에는 시간이 듭니다. 그 시간이 나중에 증거의 주인을 지킵니다.",
            cognition: { inference: 2 },
          },
          {
            id: "c1_route_sale_bundle",
            label: "묶음 매각으로 현금을 최대한 빨리 확보한다",
            effect: { capital: 12, time: 5, trust: -8, legitimacy: -6, humanCost: 4, fatigue: -3 },
            voice: "현금이 먼저라는 판단으로, 묶음 그대로 넘긴다.",
            echo: "묶음은 빠르게 팔리고, 무엇이 함께 팔렸는지는 나중에 밝혀집니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c1_route_sale_hold",
            label: "매각을 보류하고 고객 고지부터 보낸다",
            effect: { trust: 9, legitimacy: 5, capital: -8, time: -5, fatigue: 7 },
            voice: "고객이 뉴스로 먼저 알게 하지 않으려고, 매각을 멈추고 고지부터 보낸다.",
            echo: "고지는 매각가를 떨어뜨리지만, 고객의 선택권을 되돌립니다.",
            cognition: { persistence: 1, reframing: 1 },
          },
        ],
        finalTitle: "팔지 않은 증거",
        finalText: "현금이 바닥나기까지 여덟 시간, 자산 검토실 벽의 목록 석 장에는 줄이 그어진 항목이 늘었습니다. 넥스트마일은 최종 서명본을 보내 놓고 답을 기다립니다. 한서윤이 '기타 무형자산' 줄 앞에 섭니다. '이 한 줄을 넣으면 오늘 밤에 입금돼요. 빼면 값이 내려가고 날짜가 밀리고요.' 그가 운영 로그 사본이 담긴 저장 장치를 탁자에 올려놓습니다. '여기 든 건 주문 기록만이 아니에요. 장부를 누가 언제 고쳤는지도 들어 있어요. 팔면 그것도 같이 가요.' 창밖으로 거점 창고에서 돌아오는 배송 트럭 불빛이 줄지어 지나갑니다. 회사는 팔리면 남습니다. 무엇을 팔지 않을지는 지금 정해야 합니다.",
        finalMemo: ["운영 로그 사본에 장부 수정 기록이 들어 있음", "현금 압박이 커짐", "고객에게 알릴지는 아직 정하지 않음"],
        finalChoices: [
          {
            id: "a",
            label: "매각 목록에서 로그와 고객 데이터를 빼고 그 사실을 공지한다",
            effect: { legitimacy: 9, trust: 7, capital: -8, time: -6, fatigue: 8 },
            voice: "기록까지 팔 수는 없다고 판단하고, 목록에서 빼낸 사실을 그대로 공지한다.",
            echo: "빠진 항목을 공지하면 인수자는 값을 낮춥니다. 로그는 회사에 남습니다.",
            cognition: { persistence: 2, inference: 1 },
          },
          {
            id: "b",
            label: "묶음 그대로 넘기고 고객 고지는 계약 뒤로 미룬다",
            effect: { capital: 13, time: 5, trust: -9, legitimacy: -6, humanCost: 5, fatigue: -4 },
            voice: "협상을 흔들지 않으려고, 묶음 그대로 넘기고 고지는 계약 뒤로 미룬다.",
            echo: "계약은 성사되고, 고객은 자기 기록이 어디로 갔는지 마지막에 압니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c",
            label: "인수자에게 기록 보존 의무를 계약 조건으로 건다",
            effect: { trust: 8, legitimacy: 8, capital: -5, time: -5, fatigue: 6 },
            voice: "파는 대신 조건을 붙이겠다는 듯, 인수자에게 기록 보존 의무를 건다.",
            echo: "보존 의무는 계약서에 남고, 지켜지는지는 다음 사람이 확인해야 합니다.",
            cognition: { reframing: 2 },
          },
        ],
      },
      start_investigate: {
        route: "c1_route_investigate",
        final: "c1_final_investigate",
        phase: "AUDIT ROUTE",
        title: "멈춘 숫자 사이의 빈칸",
        speaker: "에코",
        text: "플로우온 본사 8층 자료실, 문서 상자가 벽을 따라 쌓여 있고 에코의 단말이 접이식 탁자 위에 놓여 있습니다. 안건을 고르기 전에 원자료부터 맞춰 보자 감축안, 자금안, 매각안의 계산 근거가 같은 자리에서 끊깁니다. 지난 8개월치 매출 기록입니다. 날짜는 이어지는데 그 구간만 고친 이력이 비어 있습니다. 에코는 그 구간을 누락 로그라고 부르고 테두리를 칩니다. '세 안건은 모두 이 구간의 숫자를 그대로 믿고 계산했습니다. 이 구간이 틀리면 셋 다 틀립니다. 어느 안을 고르느냐보다 이 빈칸을 누가 만들었느냐가 먼저입니다.' 복도에서는 재무회의를 시작한다고 사람들을 부르는 소리가 들립니다.",
        memo: ["세 대안이 같은 누락 로그를 공유", "감사 시간 동안 현금 압박이 커짐", "누락 구간을 만든 계정: 아직 확인 안 됨"],
        triggers: ["curiosity", "system", "responsibility"],
        routeChoices: [
          {
            id: "c1_route_investigate_freeze",
            label: "세 안건을 멈추고 누락 로그를 먼저 복구한다",
            effect: { legitimacy: 9, trust: 6, capital: -8, time: -8, fatigue: 8 },
            voice: "세 안건이 같은 빈칸을 지나갔다는 걸 알고, 전부 멈춘다.",
            echo: "멈추면 손실은 커지지만, 같은 빈칸이 네 번째로 반복되지 않습니다.",
            cognition: { inference: 2, persistence: 1 },
          },
          {
            id: "c1_route_investigate_shadow",
            label: "겉으로는 진행하며 뒤에서 로그만 추적한다",
            effect: { capital: 5, time: 4, trust: -5, legitimacy: -4, fatigue: 4 },
            voice: "겉으로는 진행하는 척하며, 뒤에서 로그만 조용히 따라간다.",
            echo: "조용한 추적은 속도를 지키지만, 들키는 순간 조사 자체가 의심받습니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c1_route_investigate_share",
            label: "누락 사실을 공개하고 공동 조사로 전환한다",
            effect: { trust: 8, legitimacy: 8, capital: -7, time: -6, fatigue: 7 },
            voice: "혼자 쥐고 있을 문제가 아니라고 보고, 누락 사실을 공개한다.",
            echo: "공개된 조사에는 참여자가 늘고, 결론의 주인은 당신 혼자가 아니게 됩니다.",
            cognition: { reframing: 2 },
          },
        ],
        finalTitle: "첫 사건의 진짜 시작점",
        finalText: "현금이 바닥나기까지 여덟 시간, 자료실 탁자에는 복구된 기록이 날짜순으로 깔려 있습니다. 비어 있던 여덟 달 가운데 여섯 달이 돌아왔습니다. 장부는 매번 월말 마지막 영업일 저녁에 고쳐졌고, 그때마다 보고된 부채비율(회사 빚이 자기 돈의 몇 배인지 보는 숫자)은 180% 바로 아래에서 멈췄습니다. 에코가 마지막 장에 한 줄을 띄웁니다. '이 회사의 위기는 이번 주에 생긴 것이 아닙니다. 누군가 같은 빈칸을 되풀이해 만든 기록입니다. 원자료는 결론을 늦췄지만 물어야 할 사람을 바꿨습니다.' 복도에서는 세 안건 가운데 하나를 오늘 안에 골라 달라는 전화가 계속 울립니다.",
        finalMemo: ["누락 로그가 고쳐진 시각이 전부 월말 저녁으로 모임", "세 안건의 결론은 늦어졌고 현금은 여덟 시간치", "이 기록을 누구와 함께 볼지 아직 정하지 않음"],
        finalChoices: [
          {
            id: "a",
            label: "누락 로그와 작성자를 함께 공개하고 세 안건을 재심사한다",
            effect: { legitimacy: 10, trust: 6, capital: -7, time: -8, fatigue: 8 },
            voice: "빈칸을 만든 손을 찾아야 한다고 보고, 로그와 작성자를 함께 연다.",
            echo: "작성자를 공개하면 세 안건은 다시 열립니다. 오늘의 결론은 늦어집니다.",
            cognition: { inference: 2, persistence: 1 },
          },
          {
            id: "b",
            label: "감사를 접고 가장 빠른 안건 하나만 실행한다",
            effect: { capital: 10, time: 6, trust: -8, legitimacy: -7, humanCost: 5, fatigue: -3 },
            voice: "조사보다 생존이 먼저라는 판단으로, 감사를 접고 한 안건만 실행한다.",
            echo: "가장 빠른 안건은 오늘을 삽니다. 누락 로그는 다음 사건에서 다시 나타납니다.",
            cognition: { risk: 2 },
          },
          {
            id: "c",
            label: "감사 권한을 외부 회계인에게 넘기고 결과를 기다린다",
            effect: { trust: 9, legitimacy: 7, capital: -6, time: -6, fatigue: 6 },
            voice: "내가 판정자가 되지 않으려고, 감사 권한을 외부 회계인에게 넘긴다.",
            echo: "권한을 넘기면 결과를 기다려야 합니다. 대신 결론에 당신의 이해가 섞이지 않습니다.",
            cognition: { reframing: 2 },
          },
        ],
      },
    },
    system: {
      route: "c1_route_system",
      final: "c1_final_system",
      title: "선택지 밖에서 발견한 첫 규칙",
      speaker: "에코",
      text: "세 안건 가운데 하나를 거는 대신 셋을 한 표에 놓고 보자고 하자 에코가 8층 상황실 벽면 화면을 비웁니다. 절감, 자금, 매각(사업이나 자산을 팔아 돈을 마련하는 것). 세 안의 계산표가 반투명하게 겹쳐지고, 겹친 자리에 같은 칸 하나가 진하게 남습니다. 세 안 모두 같은 기준표 한 장에서 숫자를 가져왔습니다. 표 머리에는 만든 부서도 날짜도 없습니다. 에코가 한 줄을 띄웁니다. '위기는 하나가 아니었습니다. 같은 기준표가 세 번 다른 이름으로 불렸습니다. 어느 안을 골라도 이 표가 먼저 답을 정합니다.' 상황실에 있던 사람들이 처음으로 화면이 아니라 서로를 봅니다.",
      memo: ["세 안의 계산표가 같은 칸에서 겹침", "모든 해결책이 같은 기준표를 통과함", "기준표 머리에 작성 부서와 날짜가 없음"],
      routeChoices: [
        {
          id: "c1_route_system_trace",
          label: "기준표를 누가 언제 고쳤는지부터 되짚는다",
          effect: { legitimacy: 8, trust: 3, capital: -4, time: -6, fatigue: 6 },
          voice: "세 해결책이 같은 표를 지났다는 걸 보고, 그 표를 누가 고쳤는지 되짚는다.",
          echo: "표의 이력을 열면 사건은 회계 문제에서 설계 문제로 옮겨 갑니다.",
          cognition: { inference: 2, persistence: 1 },
        },
        {
          id: "c1_route_system_use",
          label: "기준표는 그대로 두고 가장 빠른 안건을 밀어붙인다",
          effect: { capital: 9, time: 6, trust: -6, legitimacy: -5, humanCost: 4, fatigue: -4 },
          voice: "지금은 원인을 캘 때가 아니라고 판단하고, 표는 그대로 두고 밀어붙인다.",
          echo: "표를 건드리지 않으면 오늘은 빨라지고, 같은 표가 다음 사건도 통과시킵니다.",
          cognition: { risk: 2 },
        },
        {
          id: "c1_route_system_open",
          label: "기준표를 회의 밖 사람들에게 먼저 보여준다",
          effect: { trust: 8, legitimacy: 6, capital: -5, time: -5, fatigue: 6 },
          voice: "회의실 안에서만 도는 기준이 문제라고 보고, 밖의 사람들에게 먼저 보여준다.",
          echo: "밖에서 읽히는 순간 기준은 회사의 것이 아니라 기록이 됩니다.",
          cognition: { reframing: 2 },
        },
      ],
      finalTitle: "같은 표를 지나간 세 안건",
      finalText: "현금이 바닥나기까지 여덟 시간, 상황실 벽면 화면에 에코가 절감안과 자금안과 매각안을 한 표 위에 겹쳐 띄웁니다. 겹친 자리에 같은 기준표 한 장이 남습니다. 세 안 모두 그 표에서 숫자를 가져왔고, 넥스트마일 협상서의 인수 금액도 같은 표에서 나왔습니다. 표 머리에는 만든 부서도 고친 날짜도 없습니다. 에코가 한 줄을 띄웁니다. '세 안건은 같은 기준표를 통과했습니다. 표를 그대로 두면 네 번째 안건도 같은 자리에서 막힙니다.' 탁자 위에서 재무책임자의 전화기가 진동하다 멎고 다시 진동합니다. 그는 받지 않고 화면만 봅니다.",
      finalMemo: ["세 안건이 같은 기준표를 통과함", "기준표를 고친 사람과 날짜: 아직 열리지 않음", "현금 소진까지 8시간"],
    },
    finalChoices: [
      {
        id: "a",
        label: "공통 기준표를 공개하고 모든 안건을 재심사한다",
        effect: { legitimacy: 9, trust: 6, capital: -7, time: -7, fatigue: 8 },
        voice: "기준표가 문제의 주어라고 보고, 공개한 뒤 전부 다시 심사한다.",
        echo: "재심사는 시간을 크게 쓰지만, 세 위기가 하나의 원인으로 정리됩니다.",
        cognition: { inference: 2, persistence: 1 },
      },
      {
        id: "b",
        label: "기준표는 숨기고 가장 빠른 안건만 실행한다",
        effect: { capital: 10, time: 5, trust: -8, legitimacy: -6, humanCost: 5, fatigue: -3 },
        voice: "설명할 시간이 없다는 이유로, 표는 덮고 가장 빠른 길만 남긴다.",
        echo: "덮은 기준표는 다음 사건에서 같은 빈칸을 다시 만들어 냅니다.",
        cognition: { risk: 2 },
      },
      {
        id: "c",
        label: "기준표 작성 권한을 내 손 밖으로 넘긴다",
        effect: { trust: 8, legitimacy: 7, capital: -5, time: -5, fatigue: 6 },
        voice: "이 표를 내가 계속 쥐면 안 된다고 판단하고, 작성 권한을 밖으로 넘긴다.",
        echo: "권한을 넘기면 당신의 기준은 약해지고, 그 기준을 검증할 사람이 생깁니다.",
        cognition: { reframing: 2 },
      },
    ],
  },
  // CASE 02 already walks its authored middle (its `writtenRoutes`).
  routeBody: {
    routes: {
      c1_route_investigate: { entry: "accounting", tail: "c1_witness_reaction", final: "c1_final_investigate" },
      c1_route_layoff: { entry: "payday", tail: "c1_assembly_reaction", final: "c1_final_layoff" },
      c1_route_sale: { entry: "competitor", tail: "c1_bargain_reaction", final: "c1_final_sale" },
      c1_route_funding: { entry: "board", tail: "c1_verdict_reaction", final: "c1_final_funding" },
      c1_route_system: { entry: "c1_branch_people", tail: "c1_branch_people_follow", final: "c1_final_system" },
    },
  },
  evidencePlan: {
    node: "c1_evidence_turn",
    result: "c1_aftershock",
    // The other cases offer the turnaround on the route node, two scenes in.
    // Case 01 cannot: a season hands out one clue per case, the first clue can
    // only land on the second decision, and no case 01 route reaches trust 55
    // by then -- so FIELD ACCESS was unreachable and the locked button was a
    // promise the first case could never keep. Offered on the route finals
    // instead, where trust reaches 67-82 and a clue has had time to arrive.
    sourceRoutes: ["c1_final_layoff", "c1_final_funding", "c1_final_sale", "c1_final_investigate", "c1_final_system"],
    requiredAuthority: "FIELD ACCESS",
    entryVoice: "세 안건의 계산 근거를 단서 위에 펼쳐, 셋이 같은 표에서 나왔는지 가늠한다.",
    entryEcho: "계산 근거를 펼치면 세 해결책이 하나의 원인으로 묶입니다.",
    title: "첫 단서가 세 안건을 한 줄로 묶는다",
    speaker: "에코",
    text: "쥐고 있던 단서를 세 안건의 계산 근거에 대자 화면의 표들이 한 줄로 정렬됩니다. 감축안의 절감액, 자금안의 필요액, 매각안의 인수 금액이 모두 같은 기준표 한 장에서 계산됐습니다. 그리고 그 기준표를 고친 기록이, 장부의 누락 로그와 공개되지 않은 급여표를 고친 기록과 같은 계정에서 끝납니다. 작성자 칸에 사람 이름은 없습니다. 에코가 세 기록의 시각을 나란히 놓습니다. '서로 다른 해결책이 셋 있었던 것이 아닙니다. 같은 손이 만든 표가 답을 세 가지 모양으로 내놓았습니다. 이제 정할 것은 어느 안이 아니라, 이 표를 누가 다시 쓰느냐입니다.'",
    memo: ["숨은 급여표와 누락 로그가 같은 작성자를 가리킴", "세 안건의 효과가 하나의 기준표에서 계산됨", "이 연결을 어디까지 공개할지 아직 정하지 않음"],
    triggers: ["curiosity", "system", "responsibility"],
    entryEffect: { legitimacy: 4, trust: 3, time: -3, fatigue: 3 },
    choices: [
      {
        id: "c1_evidence_turn_public",
        label: "기준표와 작성자를 함께 공개한다",
        effect: { legitimacy: 10, trust: 4, capital: -7, time: -6, fatigue: 7 },
        voice: "표와 그 표를 쓴 사람을 함께 세워야 한다고 보고, 둘 다 공개한다.",
        echo: "작성자가 드러나면 기준표는 실수가 아니라 결정이 됩니다.",
        cognition: { inference: 2, persistence: 1 },
      },
      {
        id: "c1_evidence_turn_private",
        label: "작성자는 숨기고 기준표만 내부 수정한다",
        effect: { capital: 6, trust: -4, legitimacy: -3, time: 4, humanCost: 3, fatigue: -3 },
        voice: "사람은 지키고 구조만 고치겠다는 듯, 작성자는 가리고 표만 손본다.",
        echo: "이름을 가린 수정은 빠릅니다. 같은 사람이 다음 표도 씁니다.",
        cognition: { risk: 2 },
      },
      {
        id: "c1_evidence_turn_transfer",
        label: "다음 사건 담당자에게 원본 검증권을 넘긴다",
        effect: { trust: 9, legitimacy: 6, capital: -5, fatigue: 6 },
        voice: "내가 검증하면 같은 눈이 반복된다고 보고, 다음 담당자에게 넘긴다.",
        echo: "검증권을 넘기면 이번 결론은 늦어지고, 다음 사건의 시작은 달라집니다.",
        cognition: { reframing: 2 },
      },
    ],
    entryLabel: "세 안건이 지나간 기준표를 단서로 연다",
  },
  // 사건 01 had no openings while it was the season's door. The 프롤로그 put
  // five cases in front of it, so what the analyst carried down to 트리거랩
  // three years ago is what they are holding when 한서윤 slides the training
  // file across the desk.
  openingRoutes: {
    p5_after_hold: "c1_start_hold",
    p5_after_record: "c1_start_record",
    p5_after_alone: "c1_start_alone",
  },
  openingCopy: {
    c1_start_hold: ["벽에 3년 붙어 있던 이름들", "한서윤", "트리거랩 첫날 책상 앞 벽에 붙인 종이는 테이프를 세 번 갈아 붙이는 동안 그대로 있었습니다. 이름 열한 개가 적힌 종이입니다. 그 아래에서 햇수로 3년을 앉아 있다가 오늘 아침 한서윤이 서류철 하나를 내밉니다. '훈련용 사례예요. 제한 시간은 72시간이고요.' 표지 밑단에 인쇄가 조금 남아 있는데, 대출번호 2023-0412입니다. 당신은 벽의 이름들을 등 뒤에 두고 그 서류철을 폅니다. 수도권 당일배송망을 돌리는 물류 플랫폼 플로우온, 직원 1,140명. 투자금 입금이 취소됐고 현금은 72시간 뒤 바닥난다고 적혀 있습니다. 3년 전 당신이 멈추려던 회사가, 지금 멈추는 중입니다.", ["책상 앞 벽 -- 3년간 붙어 있던 이름 열한 개", "훈련용 사례 표지 밑단: 2023-0412", "플로우온 현금 소진까지 72h"]],
    c1_start_record: ["B2에서 3년 만에 올라온 상자", "한서윤", "3년 전 사본과 날짜 메모를 넣어 둔 B2의 그 상자는 계절이 바뀌어도 온도가 같은 방에서 매듭 그대로 있었습니다. 오늘 아침 한서윤이 훈련용 사례라며 서류철을 내밀었을 때, 당신은 표지 밑단의 2023-0412를 먼저 읽고 계단으로 B2까지 내려갔습니다. 상자는 열려 있었습니다. 끈은 다시 묶여 있는데 당신이 묶은 매듭이 아닙니다. 올라와서 서류철을 폅니다. 수도권 당일배송망을 돌리는 물류 플랫폼 플로우온, 직원 1,140명. 투자금 입금이 취소됐고 현금은 72시간 뒤 바닥난다고 적혀 있습니다. 당신이 3년 전에 쓴 숫자와 오늘 아침의 숫자가 같은 줄에서 만납니다.", ["B2 상자 -- 매듭이 다시 묶여 있음", "훈련용 사례 표지 밑단: 2023-0412", "플로우온 현금 소진까지 72h"]],
    c1_start_alone: ["아무것도 들고 오지 않은 3년", "한서윤", "3년 전 가방을 비우고 빈 책상 하나로 시작했습니다. 그 뒤로 사건이 쌓였고, 당신은 이 4층을 지하라고 부르는 사람이 되었습니다. 오늘 아침 한서윤이 훈련용 사례라며 서류철을 내밉니다. 표지 밑단에 2023-0412가 남아 있는데, 당신에게는 그 번호와 맞춰 볼 종이가 한 장도 없습니다. 기억만 있습니다. 서류철을 폅니다. 수도권 당일배송망을 돌리는 물류 플랫폼 플로우온, 직원 1,140명. 투자금 입금이 취소됐고 현금은 72시간 뒤 바닥난다고 적혀 있습니다. 숫자는 낯익은데, 당신은 자기 기억이 증거가 되지 않는다는 것을 알고 있습니다.", ["3년 전 기록 -- 보관본 없음", "훈련용 사례 표지 밑단: 2023-0412", "플로우온 현금 소진까지 72h"]],
  },
  openingSignatures: {
    c1_start_hold: {
      label: "벽의 이름들과 이 서류철의 번호가 같은 사건인지 먼저 확인한다",
      effect: { trust: 7, legitimacy: 6, time: -5, capital: -3, fatigue: 5 },
      cognition: { persistence: 2 },
      next: "c1_route_investigate",
      voice: "훈련용 사례라는 말을 그대로 믿기 전에, 벽의 이름들과 이 서류철의 번호가 같은 사건인지 먼저 확인한다.",
      echo: "맞춰 보면 3년 전 그 회사가 맞습니다. 확인하는 데 쓴 시간만큼 72시간이 줄어듭니다.",
    },
    c1_start_record: {
      label: "B2 상자의 매듭이 언제 다시 묶였는지부터 묻는다",
      effect: { legitimacy: 8, trust: 4, time: -6, capital: -2, fatigue: 5 },
      cognition: { inference: 2 },
      next: "c1_route_investigate",
      voice: "누군가 먼저 열어 본 상자여서, B2 상자의 매듭이 언제 다시 묶였는지부터 묻는다.",
      echo: "물으면 열람 기록이 나옵니다. 기록에는 당신 사번도 한 줄 있습니다. 당신이 내려가지 않은 날짜입니다.",
    },
    c1_start_alone: {
      label: "기억만 있다는 사실을 한서윤에게 먼저 말한다",
      effect: { trust: 9, legitimacy: -3, humanCost: -3, time: -3, capital: -2, fatigue: 4 },
      cognition: { reframing: 2 },
      next: "c1_route_investigate",
      voice: "기억을 증거인 척 내밀 수는 없다며, 기억만 있다는 사실을 한서윤에게 먼저 말한다.",
      echo: "말하면 한서윤이 화면을 한 칸 내립니다. 그리고 '그럼 이번에는 적어 두세요'라고 합니다. 증명할 것이 없다는 걸 그도 압니다.",
    },
  },
  setting: { place: "플로우온 본사 8층 상황실", clock: "현금 소진 D-72h" },
  sceneContext: {
    // ---------------------------------------------------------------- CASE 01
    c1_start_hold: {
      place: "트리거랩 분석실 · 케이스데스크",
      clock: "현금 소진 D-72h",
      question: "3년 동안 벽에 붙여 둔 이름들 아래에서, 그때 그 대출번호를 다시 만났습니다. 첫 72시간을 어디에 쓰겠습니까?",
      lead: "책상 앞 벽의 종이는 테이프를 세 번 갈아 붙이는 동안 그대로 있었습니다. 오늘 아침 한서윤이 내민 훈련용 사례 표지 밑단에 2023-0412가 남아 있습니다.",
    },
    c1_start_record: {
      place: "트리거랩 분석실 · 케이스데스크",
      clock: "현금 소진 D-72h",
      question: "B2에 남겨 둔 상자의 매듭이 당신의 매듭이 아닙니다. 첫 72시간을 어디에 쓰겠습니까?",
      lead: "3년 전 사본과 날짜 메모를 넣어 둔 상자를 오늘 아침 확인하러 내려갔습니다. 상자는 열려 있었고, 올라오니 같은 번호의 서류철이 책상에 있습니다.",
    },
    c1_start_alone: {
      place: "트리거랩 분석실 · 케이스데스크",
      clock: "현금 소진 D-72h",
      question: "맞춰 볼 종이가 한 장도 없고 기억만 있습니다. 첫 72시간을 어디에 쓰겠습니까?",
      lead: "3년 전 가방을 비우고 빈 책상 하나로 시작했습니다. 오늘 아침 그때 그 대출번호가 훈련용 사례의 표지로 돌아왔습니다.",
    },
    start: {
      place: "트리거랩 분석실 · 케이스데스크",
      clock: "현금 소진 D-72h",
      question: "플로우온의 현금이 사흘 뒤 바닥납니다. 첫 72시간을 어디에 쓰겠습니까?",
      lead: "트리거랩 분석실, 배치 첫날입니다. 3년 전 KD은행 기업금융전략팀에서 반대 의견 하나를 쓴 뒤 이 지하로 내려왔습니다. 한서윤이 올려놓은 첫 파일 표지에, 그때 그 대출번호가 그대로 남아 있습니다.",
    },
    accounting: {
      place: "플로우온 본사 8층 재무회의실",
      clock: "현금 소진 D-68h",
      question: "투자자가 본 숫자와 실제 현금이 다릅니다. 이 사실을 언제, 누구에게 먼저 꺼내겠습니까?",
      lead: "자금 자료를 요청하자 장부가 열렸습니다. 그 옆에 KD은행 대출 계약서도 함께 나왔고, 제7조에 밑줄이 그어져 있습니다.",
    },
    payday: {
      place: "플로우온 풀필먼트 센터 · 야간조 대기실",
      clock: "급여 지급까지 13h",
      question: "내일 오전 9시에 급여가 나가야 합니다. 직원들에게 지금 사실을 알리겠습니까, 방안을 확정한 뒤에 알리겠습니까?",
      lead: "본사에서 차로 40분, 서울 외곽 풀필먼트 센터(주문받은 물건을 보관하고 포장해 내보내는 물류 창고)입니다. 여기 사람들은 아직 회사에 무슨 일이 벌어지는지 모릅니다.",
    },
    competitor: {
      place: "플로우온 본사 8층 협상실",
      clock: "현금 소진 D-52h",
      question: "경쟁사는 헐값 인수를, 오진우는 더 싼 대안을 내밀었습니다. 무엇을 협상 테이블에 올리겠습니까?",
      lead: "자산 검토실에서 나오자 넥스트마일의 인수(회사를 통째로 사들이는 것) 제안서가 협상실에 먼저 도착해 있었습니다. 같은 자리에 트리거랩 분석관 오진우도 앉아 있습니다.",
    },
    board: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-30h",
      question: "직원·생존·책임·투자자·협력사를 전부 지킬 수는 없습니다. 무엇을 맨 앞에 두겠습니까?",
      lead: "이틀 동안 모은 자료가 한 테이블에 올라왔습니다. 에코가 모든 항목을 동시에 만족시키는 조합이 없다고 표시합니다.",
    },
    c1_witness: {
      place: "플로우온 본사 8층 회계팀 복도",
      clock: "현금 소진 D-66h",
      question: "회계팀 막내가 문 앞에서 멈춰 섰습니다. 그가 안전하게 말할 자리를 먼저 만들겠습니까?",
      lead: "재무회의가 끝나고 복도로 나오는 길입니다. 회의에 초대받지 못했던 직원이 당신을 기다리고 있습니다.",
    },
    c1_witness_reaction: {
      place: "플로우온 본사 8층 회계팀",
      clock: "현금 소진 D-65h",
      question: "막내가 입을 연 뒤로 회계팀 전체가 입을 닫았습니다. 누구를 보호한다고 기록에 남기겠습니까?",
    },
    c1_assembly: {
      place: "플로우온 풀필먼트 센터 · 야간조 대기실",
      clock: "급여 지급까지 9h",
      question: "직원들이 원하는 건 돈보다 내일도 여기 있을지에 대한 답입니다. 약속을 어떤 형식으로 남기겠습니까?",
    },
    c1_assembly_reaction: {
      place: "플로우온 풀필먼트 센터 · 야간조 대기실",
      clock: "급여 지급까지 4h",
      question: "직원 단체방에 서로 다른 소문이 올라왔습니다. 지금 아는 것까지만 공지하겠습니까?",
    },
    c1_bargain: {
      place: "플로우온 본사 8층 협상실",
      clock: "현금 소진 D-44h",
      question: "인수 조건서의 빈칸에 누가 들어갈지 아무도 쓰지 않았습니다. 그 칸을 채운 뒤에 협상하겠습니까?",
    },
    c1_bargain_reaction: {
      place: "플로우온 본사 8층 협상실",
      clock: "현금 소진 D-40h",
      question: "협상 상대가 자리에 오지 않았습니다. 빈 의자의 사람들을 협상에 부르겠습니까?",
    },
    c1_verdict: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-24h",
      question: "자료는 다 모였는데 결론은 더 멀어졌습니다. 내일의 비용을 누가 들게 하겠습니까?",
    },
    c1_verdict_reaction: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-20h",
      question: "반재욱이 마지막으로 묻습니다. 이 결론을 가장 먼저 듣게 될 사람은 누구입니까?",
    },
    c1_branch_people: {
      place: "플로우온 본사 8층 협상실",
      clock: "현금 소진 D-42h",
      question: "넥스트마일 협상서의 빈칸을 사람 이름으로 채우려 합니다. 누구의 이름부터 적겠습니까?",
    },
    c1_branch_people_follow: {
      place: "플로우온 본사 8층 협상실",
      clock: "현금 소진 D-38h",
      question: "서명 뒤 첫 전화는 계약서에 없는 사람에게서 왔습니다. 그 약속을 무엇으로 보증하겠습니까?",
    },
    c1_route_layoff: {
      place: "플로우온 본사 8층 인사회의실",
      clock: "현금 소진 D-70h",
      question: "감축 명단이 열렸습니다. 대상자에게 먼저 알리겠습니까, 절감액을 먼저 확정하겠습니까?",
      lead: "구조조정을 검토하겠다고 말한 직후입니다. 회의실 밖 대기 명단이 사건의 중심으로 들어옵니다.",
    },
    c1_route_funding: {
      place: "플로우온 본사 8층 투자 협의실",
      clock: "현금 소진 D-70h",
      question: "긴급 자금 조건서에 비공개 심사 조항이 있습니다. 시간을 살 것인지, 설명 권한을 지킬 것인지 정해야 합니다.",
      lead: "단기 자금 조달에 집중하겠다고 말한 직후입니다. 돈은 시간을 벌어주지만 조건서는 다음 판단의 공개 범위를 먼저 묻습니다.",
    },
    c1_route_sale: {
      place: "플로우온 본사 8층 자산 검토실",
      clock: "현금 소진 D-70h",
      question: "매각 목록에 고객 데이터와 운영 로그가 섞여 있습니다. 무엇을 떼어내고 팔겠습니까?",
      lead: "핵심 사업부 매각 가능성을 열겠다고 말한 직후입니다. 한서윤이 먼저 올라와 벽에 목록을 붙여 두었습니다.",
    },
    c1_route_investigate: {
      place: "플로우온 본사 8층 자료실",
      clock: "현금 소진 D-70h",
      question: "원자료를 펼쳤지만 숫자 사이에 빈칸이 있습니다. 어디부터 열어보겠습니까?",
      lead: "결론을 미루는 사람처럼 보일 위험을 감수하고, 안건을 고르기 전에 자료부터 맞춰 보기로 한 직후입니다.",
    },
    c1_route_system: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-70h",
      question: "선택지 밖으로 판을 다시 짜자 사건의 규칙이 반응했습니다. 이 규칙을 어떻게 쓰겠습니까?",
      lead: "준비된 보기 셋 가운데 어느 것도 걸지 않고 다시 짠 판이 사건 파일에 그대로 기록됐습니다.",
    },
    c1_final_layoff: {
      place: "플로우온 본사 8층 인사회의실",
      clock: "현금 소진 D-8h",
      question: "절감액은 확보됐고 이름은 남았습니다. 이 감축을 무엇으로 마무리하겠습니까?",
    },
    c1_final_funding: {
      place: "플로우온 본사 8층 투자 협의실",
      clock: "현금 소진 D-8h",
      question: "자금은 서명만 남았고 설명 권한은 줄어듭니다. 이 조건을 어디까지 받아들이겠습니까?",
    },
    c1_final_sale: {
      place: "플로우온 본사 8층 자산 검토실",
      clock: "현금 소진 D-8h",
      question: "매각으로 회사는 남습니다. 팔지 않고 지킬 것을 지금 정해야 합니다.",
    },
    c1_final_investigate: {
      place: "플로우온 본사 8층 자료실",
      clock: "현금 소진 D-8h",
      question: "원자료가 사건의 시작점을 다시 가리킵니다. 이 발견을 어디에 쓰겠습니까?",
    },
    c1_final_system: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-8h",
      question: "세 안건이 같은 기준표를 지나갔다는 것이 드러났습니다. 그 기준표를 남기겠습니까, 닫겠습니까?",
    },
    c1_evidence_turn: {
      place: "플로우온 본사 8층 상황실",
      clock: "현금 소진 D-6h",
      question: "모은 단서가 세 안건을 한 줄로 묶습니다. 이 연결을 공식 기록으로 올리겠습니까?",
    },
    c1_aftershock: {
      place: "플로우온 본사 8층 상황실",
      clock: "결정 다음 날 오전",
      question: "결정 다음 날, 숫자보다 사람들의 반응이 먼저 도착했습니다. 누구에게 먼저 설명하겠습니까?",
      lead: "사건은 닫혔지만 하루가 더 남았습니다. 당신이 남긴 약속을 사람들이 각자 다르게 읽고 있습니다.",
    },
  },
  clue: {
    id: "c1-hidden-ledger",
    title: "숨은 급여표",
    text: "공식 보고서보다 먼저 움직인 돈의 흔적이 있습니다. 누군가는 이미 다음 사건을 알고 있었습니다.",
  },
  outcomes: {
    c1_after_people: { tag: "사람을 먼저 세운 결말", title: "급여명세서보다 먼저 이름을 불렀다", text: "직원과 협력사는 당신의 결정을 완전히 믿지는 않지만, 적어도 누가 비용을 떠안는지 알게 됐습니다. 다음 사건은 사람을 보호한 대가로 더 느리게 시작됩니다." },
    c1_after_numbers: { tag: "숫자를 공개한 결말", title: "현금 흐름표가 약속이 되었다", text: "회사는 더 많은 질문을 받게 됐지만, 숨겨진 손실은 줄었습니다. 다음 사건은 기록을 믿을지 사람을 믿을지 묻습니다." },
    c1_after_silence: { tag: "침묵을 택한 결말", title: "조용한 하루를 샀다", text: "자금은 하루를 벌었지만 직원들의 믿음은 늦게 회복됩니다. 다음 사건에는 설명되지 않은 비용이 따라옵니다." },
  },
  carryovers: {
    c1_after_people: { trust: 6, humanCost: -3, fatigue: 4 },
    c1_after_numbers: { capital: -4, legitimacy: 5, fatigue: 2 },
    c1_after_silence: { capital: 5, trust: -7, legitimacy: -4 },
  },
  // 사건 01 follows the 프롤로그 now, so it has a predecessor for the first
  // time: what the analyst carried down to 트리거랩 is what the first table
  // asks them to put down.
  continuityChallenges: {
    p5_after_hold: { id: "protect-trust", title: "벽의 이름을 오늘의 이름과 잇기", text: "3년 동안 벽에 붙여 둔 열한 개의 이름은 기억이지 기록이 아닙니다. 오늘 72시간 안에서 그 이름들이 누구를 가리키는지 보여 주는 선택을 찾으면 숨은 단서가 열릴 수 있습니다." },
    p5_after_record: { id: "repair-legitimacy", title: "다시 묶인 매듭을 되찾기", text: "B2의 상자는 당신이 묶은 매듭이 아닙니다. 남겨 둔 기록이 누구의 손을 거쳤는지 먼저 묻는 선택이 공정함을 되찾고 압박을 낮춥니다." },
    p5_after_alone: { id: "protect-trust", title: "기억을 혼자 쥐지 않기", text: "가방을 비우고 시작한 3년은 증명할 것을 하나도 남기지 않았습니다. 기억만 있다는 사실을 옆 사람에게 먼저 꺼내 놓는 선택이 압박을 낮춥니다." },
  },
};
