/**
 * What each case is, and what all twelve turn out to be.
 *
 * The season used to be an anthology: seven unrelated organisations, each with
 * its own crisis, strung together by a lab that watched the analyst react. That
 * made every case disposable -- nothing the player learned in 사건 01 could be
 * used in 사건 04, so nothing in 사건 01 mattered.
 *
 * They are now one chain. A single bad loan -- the 310억 KD은행 lent 플로우온
 * three years ago -- runs under all seven: 사건 01 is the loan collapsing, 02 is
 * the cover-up of its paperwork, 03 and 04 are the two places the bank tried to
 * move the loss to, 05 is where the loss finally lands on people who never
 * borrowed anything, 06 is what the chain does to the analyst in the next chair,
 * 07 is the posting that was meant to end it, 08 follows the money the chain paid
 * out to the man at the top of it, 09 goes back to 플로우온 to save it and charge
 * the people who broke it on the same table, 10 is the bill the people who won
 * it are handed the week after, 11 is the first room the whole country can see
 * into -- a 국정감사 with the man at the top of the chain summoned and absent --
 * 12 walks into the lives the loan landed on, where a compensation fund comes
 * with a condition, and the finale is the empty signature box the whole thing
 * hangs from.
 */
export const CASE_SEQUENCE = ["case01", "case02", "case03", "case04", "case05", "case06", "case07", "case08", "case09", "case10", "case11", "case12", "case13", "case14", "case15", "case16", "case17", "case18", "case19", "case20", "case21", "case22", "case23", "case24", "case25", "case26", "case27", "case28", "case29", "case30", "case31", "case32", "case33", "case34", "case35", "case36", "case37", "case38", "case39", "case40", "case41", "case42", "case43", "case44", "case45", "case46", "case47", "case48", "case49", "final"];
export const CASE_START_NODES = {
  case01: "start",
  case02: "c2_start",
  case03: "c3_start",
  case04: "c4_start",
  case05: "c5_start",
  case06: "c6_start",
  case07: "c7_start",
  case08: "c8_start",
  case09: "c9_start",
  case10: "c10_start",
  case11: "c11_start",
  case12: "c12_start",
  case13: "c13_start",
  case14: "c14_start",
  case15: "c15_start",
  case16: "c16_start",
  case17: "c17_start",
  case18: "c18_start",
  case19: "c19_start",
  case20: "c20_start",
  case21: "c21_start",
  case22: "c22_start",
  case23: "c23_start",
  case24: "c24_start",
  case25: "c25_start",
  case26: "c26_start",
  case27: "c27_start",
  case28: "c28_start",
  case29: "c29_start",
  case30: "c30_start",
  case31: "c31_start",
  case32: "c32_start",
  case33: "c33_start",
  case34: "c34_start",
  case35: "c35_start",
  case36: "c36_start",
  case37: "c37_start",
  case38: "c38_start",
  case39: "c39_start",
  case40: "c40_start",
  case41: "c41_start",
  case42: "c42_start",
  case43: "c43_start",
  case44: "c44_start",
  case45: "c45_start",
  case46: "c46_start",
  case47: "c47_start",
  case48: "c48_start",
  case49: "c49_start",
  final: "f_start",
};
export const CASE_RESULT_NODES = {
  case01: "result",
  case02: "case02_result",
  case03: "case03_result",
  case04: "case04_result",
  case05: "case05_result",
  case06: "case06_result",
  case07: "case07_result",
  case08: "case08_result",
  case09: "case09_result",
  case10: "case10_result",
  case11: "case11_result",
  case12: "case12_result",
  case13: "case13_result",
  case14: "case14_result",
  case15: "case15_result",
  case16: "case16_result",
  case17: "case17_result",
  case18: "case18_result",
  case19: "case19_result",
  case20: "case20_result",
  case21: "case21_result",
  case22: "case22_result",
  case23: "case23_result",
  case24: "case24_result",
  case25: "case25_result",
  case26: "case26_result",
  case27: "case27_result",
  case28: "case28_result",
  case29: "case29_result",
  case30: "case30_result",
  case31: "case31_result",
  case32: "case32_result",
  case33: "case33_result",
  case34: "case34_result",
  case35: "case35_result",
  case36: "case36_result",
  case37: "case37_result",
  case38: "case38_result",
  case39: "case39_result",
  case40: "case40_result",
  case41: "case41_result",
  case42: "case42_result",
  case43: "case43_result",
  case44: "case44_result",
  case45: "case45_result",
  case46: "case46_result",
  case47: "case47_result",
  case48: "case48_result",
  case49: "case49_result",
  final: "final_result",
};
export const RESULT_NODE_IDS = new Set(Object.values(CASE_RESULT_NODES));

export const nodeOrders = {
  case01: ["start", "accounting", "payday", "competitor", "board", "final"],
  case02: ["c2_start", "c2_logs", "c2_meeting", "c2_pressure", "c2_final"],
  case03: ["c3_start", "c3_split", "c3_score", "c3_trap", "c3_final"],
  case04: ["c4_start", "c4_offer", "c4_leak", "c4_vote", "c4_final"],
  case05: ["c5_start", "c5_map", "c5_blame", "c5_collapse", "c5_final"],
  case06: ["c6_start", "c6_desk", "c6_logs", "c6_panel", "c6_final"],
  case07: ["c7_start", "c7_ledger", "c7_counter", "c7_paper", "c7_final"],
  case08: ["c8_start", "c8_trail", "c8_gallery", "c8_bait", "c8_final"],
  case09: ["c9_start", "c9_ledger", "c9_family", "c9_timing", "c9_final"],
  case10: ["c10_start", "c10_locker", "c10_claim", "c10_relay", "c10_final"],
  case11: ["c11_start", "c11_script", "c11_rehearsal", "c11_sign", "c11_final"],
  case12: ["c12_start", "c12_mediation", "c12_market", "c12_memorial", "c12_final"],
  case13: ["c13_start", "c13_studio", "c13_market", "c13_lab", "c13_final"],
  case14: ["c14_start", "c14_counter", "c14_desk", "c14_class", "c14_final"],
  case15: ["c15_start", "c15_form", "c15_rooftop", "c15_gate", "c15_final"],
  case16: ["c16_start", "c16_duel", "c16_review", "c16_roof", "c16_final"],
  case17: ["c17_start", "c17_truck", "c17_office", "c17_legal", "c17_final"],
  case18: ["c18_start", "c18_lounge", "c18_party", "c18_table", "c18_final"],
  case19: ["c19_start", "c19_shelves", "c19_ward", "c19_labels", "c19_final"],
  case20: ["c20_start", "c20_server", "c20_datacenter", "c20_farewell", "c20_final"],
  case21: ["c21_start", "c21_inn", "c21_orchard", "c21_breakwater", "c21_final"],
  case22: ["c22_start", "c22_counter", "c22_factory", "c22_roleplay", "c22_final"],
  case23: ["c23_start", "c23_proxy", "c23_advisor", "c23_backstage", "c23_final"],
  case24: ["c24_start", "c24_desks", "c24_rooftop", "c24_farewell", "c24_final"],
  case25: ["c25_start", "c25_notice", "c25_standby", "c25_chatroom", "c25_final"],
  case26: ["c26_start", "c26_crane", "c26_creditors", "c26_tower", "c26_final"],
  case27: ["c27_start", "c27_queue", "c27_rumor", "c27_offer", "c27_final"],
  case28: ["c28_start", "c28_headset", "c28_ruler", "c28_factory", "c28_final"],
  case29: ["c29_start", "c29_marina", "c29_hawker", "c29_hotel", "c29_final"],
  case30: ["c30_start", "c30_bookstore", "c30_datalab", "c30_leaving", "c30_final"],
  case31: ["c31_start", "c31_archive", "c31_hallway", "c31_rooftop", "c31_final"],
  case32: ["c32_start", "c32_boxes", "c32_room", "c32_notebook", "c32_final"],
  case33: ["c33_start", "c33_room", "c33_mother", "c33_rice", "c33_final"],
  case34: ["c34_start", "c34_study", "c34_sketch", "c34_seminar", "c34_final"],
  case35: ["c35_start", "c35_sandbag", "c35_lathe", "c35_noah", "c35_final"],
  case36: ["c36_start", "c36_garden", "c36_table", "c36_father", "c36_final"],
  case37: ["c37_start", "c37_takedown", "c37_reading", "c37_source", "c37_final"],
  case38: ["c38_start", "c38_gallery", "c38_witness", "c38_plaintiff", "c38_final"],
  case39: ["c39_start", "c39_cut", "c39_mosaic", "c39_caption", "c39_final"],
  case40: ["c40_start", "c40_demo", "c40_anchor", "c40_steam", "c40_final"],
  case41: ["c41_start", "c41_drill", "c41_corridor", "c41_chamber", "c41_final"],
  case42: ["c42_start", "c42_pension", "c42_karaoke", "c42_breakwater", "c42_final"],
  case43: ["c43_start", "c43_ledger", "c43_advisor", "c43_corridor", "c43_final"],
  case44: ["c44_start", "c44_lottery", "c44_court", "c44_lunch", "c44_final"],
  case45: ["c45_start", "c45_wreath", "c45_stories", "c45_envelope", "c45_final"],
  case46: ["c46_start", "c46_cage", "c46_boot", "c46_recount", "c46_final"],
  case47: ["c47_start", "c47_steam", "c47_factory", "c47_memorial", "c47_final"],
  case48: ["c48_start", "c48_hub", "c48_engine", "c48_pen", "c48_final"],
  case49: ["c49_start", "c49_market", "c49_server", "c49_crosswalk", "c49_final"],
  final: ["f_start", "f_archive", "f_confront", "f_choice"],
};

export const caseObjectives = {
  case01: "3년 전 당신이 반대했던 그 대출의 마지막 72시간을 어떻게 닫을지 정한다",
  case02: "조작된 접속 기록이 가리키는 사람과 그 기록을 만든 손 중 어느 쪽을 먼저 보고할지 정한다",
  case03: "오진우보다 빠른 결론이 아니라, 3년 뒤에도 무너지지 않는 판을 만든다",
  case04: "은행의 상환 요구가 만들어 낸 3% 부족분을 어디까지 손댈지 정한다",
  case05: "악인이 없는 실패에서 책임과 개선 가능성을 구분한다",
  case06: "옆자리 동료의 붕괴에서 보호와 기록 중 무엇을 먼저 둘지 정한다",
  case07: "발령까지 48시간 동안 무엇을 모으고, 그 대가를 누구에게 지울지 정한다",
  case08: "윤상혁에게 이어진 돈의 흔적을 복수가 아니라 증거로 남길 방법을 정한다",
  case09: "플로우온을 살리는 계산서와 무너뜨린 사람을 벌하는 계산서를 한 테이블에 올린다",
  case10: "한 사람의 집념으로 버티던 명단을 부서지지 않는 구조로 옮기면서, 그 구조에서 밀려나는 사람을 어떻게 할지 정한다",
  case11: "모두가 보는 방에서, 3년 전 사라진 반대 의견을 누가 지웠는지 말할지 그리고 그 말에 누구의 이름을 걸지 정한다",
  case12: "조건이 붙은 배상금 앞에서, 서류가 없는 212명까지 배상 기준에 넣을지와 그 대가를 누가 치를지 정한다",
  case13: "혁신위원회의 얼굴이 되어 달라는 제안 앞에서, 212명의 배상 기준과 동료들의 자리를 대가로 '과거는 정리됐다'는 문장을 읽을지 정한다",
  case14: "착한 이름을 단 펀드가 손실을 은퇴자에게 옮기기 전에, 판매를 멈출지 고칠지 돈의 길을 쫓을지 정하십시오.",
  case15: "이민서의 정규직 전환과 11초의 진실 사이에서, 그의 선택을 대신하지 않고 곁에 선다.",
  case16: "로봇 120대가 들어오는 리스 앞에서, 야간조 80명이 나가는 문을 문자 한 통이 아닌 길로 바꿀 수 있을지와 그 대가를 누가 치를지 정한다",
  case17: "47명의 이름이 적힌 수첩을 법원에 낼지, 이름의 주인들에게 돌려줄지, 태울지 정하고 그 대가를 누가 치를지 정한다",
  case18: "KD를 벨 수 있는 칼과 함께 온 스카우트 앞에서, 오진우를 붙잡을지 조건을 걸어 보낼지 매각 자체를 막을지, 그리고 그 대가를 매각 묶음 속 누가 치를지 정한다",
  case19: "철거 전 72시간 안에 40년 치 종이 원본을 옮기고, 그 종이가 누구의 이름으로 어디에 남을지 정한다",
  case20: "자정 교체 전에, 에코가 남긴 판단 원칙과 동의 없이 쓰인 반응 기록의 주인을 지킨다",
  case21: "자기 반응이 실험 자료였다는 걸 모르는 첫 번째 참가자에게, 무엇을 언제 알릴지와 그 기록을 누가 지킬지 정한다",
  case22: "죽은 사람의 이름으로 거절된 공장의 대출 앞에서, 한 곳을 사람의 서명으로 지금 살릴지, 같은 규칙에 걸린 41곳을 늦게 다 다시 보게 할지 정한다",
  case23: "한 주씩 모은 3,118명의 표와 1분의 발언으로, 윤상혁의 사내이사 선임을 막을지 서명란 실명제와 바꿀지 기록으로만 남길지 정한다",
  case24: "트리거랩이 해체되는 일주일 동안, 흩어지는 사람들과 옮겨지는 기록 중 무엇을 먼저 지킬지 정합니다.",
  case25: "흩어진 첫 주 동안 동료들을 어떻게 붙들지, 그리고 나를 데려가려는 사람의 건물에 어떤 조건으로 들어갈지 정합니다.",
  case26: "만기가 온 평택 공사 대출 앞에서, 연장과 손실 처리와 임금 먼저 중 어떤 의견서에 이름을 남길지 정합니다.",
  case27: "캡처 한 장으로 시작된 뱅크런 앞에서, 동네 사람들의 돈과 새봄신협의 평택 몫 중 무엇을 먼저 지킬지 정합니다.",
  case28: "3분짜리 거절 대본과 6.5포인트 조항 앞에서, 한 사람의 보험금과 같은 조항에 걸린 1,318명 중 무엇을 먼저 지킬지 정합니다.",
  case29: "싱가포르 매각 서명식까지 사흘 동안, 팔려 가는 채무자와 드러날 제보자와 윤상혁의 새 자리 중 무엇을 먼저 막을지 정합니다.",
  case30: "팔려 나간 트리거랩 기록을 되찾기 위해, 흩어진 여섯 명 중 누구의 자리를 먼저 걸지 정합니다.",
  case31: "나를 믿지 않는 검사역 앞에서, 평택 PF의 미룬 손실과 그 서류에 이름이 적힌 사람들 중 무엇을 먼저 지킬지 정합니다.",
  case32: "압수수색 하루 동안, 상자에 담기는 동료들의 기록과 당신 이름이 쓰인 서명 중 무엇을 먼저 지키고 무엇을 먼저 밝힐지 정합니다.",
  case33: "신고한 사람을 비싸게 만드는 일주일 동안, 백아린의 곁과 신고의 절차와 합의의 값 중 무엇을 먼저 지킬지 정합니다.",
  case34: "아버지를 사랑하는 딸이 아버지의 기록을 들고 왔을 때, 그 기록을 누구의 손으로, 어떤 순서로 세상에 내보낼지 딸과 함께 정한다",
  case35: "물에 잠긴 사람들을 물에 잠겼다는 이유로 거절하는 기계 앞에서, 한 건씩 사람이 뒤집을지, 기준 자체를 늦게라도 바꿀지, 피해 사진을 넘기고 사흘 만에 돈을 풀지 정한다",
  case36: "사슬 전체를 이름 하나로 닫자는 회장의 제안 앞에서, 그 자리를 받을지, 조건을 걸지, 거절하고 끝까지 갈지 정합니다.",
  case37: "인터넷에 퍼진 열세 명의 반응 기록을 지울지, 남길지, 증거로 쓸지를 기록의 주인들과 함께 정한다",
  case38: "서류 없는 212명을 원고로 지키고, 동의 없이 만든 기록이 증언을 깎는 데 쓰이는 것을 막으며, 재판을 나눌지 1,740명이 함께 갈지 정한다",
  case39: "광고가 가리킨 20분과 인터뷰이들의 얼굴 사이에서, 아침 10시까지 무엇을 방송에 남길지 정합니다.",
  case40: "망설임을 감점하도록 배운 채용 점수 앞에서, 떨어진 9,412명을 사람이 다시 만나게 할지, 점수의 계산법을 모두에게 공개하게 할지, 서비스를 하룻밤에 멈출지 정한다",
  case41: "스물세 번의 '기억나지 않습니다' 앞에서 단 하나의 질문을 골라, 증명할 수 없는 대답이 이 방에서 무엇이 될지 정한다",
  case42: "쉬러 간 바닷가에서, 지난 주인의 주소 때문에 벌을 받는 새 주인과 해임안이 '정리 완료'라고 적은 마흔일곱 곳 중 무엇을 먼저 지킬지 정합니다.",
  case43: "한 사람을 내보내는 해임안이 2023년의 기록을 여는 절차가 될지 닫는 절차가 될지, 회장의 마지막 한 표 앞에서 결의문의 마지막 줄을 정한다",
  case44: "회사가 용서하고 직원들이 갚은 판결 앞에서, 방청석의 사람들 곁에 설지, 7일 안의 항소를 준비할지, 추징금을 배상으로 돌릴 협상부터 할지 정한다",
  case45: "발인(관을 장례식장에서 떠나보내는 일) 날 아침, 윤상혁의 빈칸 네 개를 채울 수 있는 원본 한 장을 가족의 뜻에 맡길지, 고인이 지운 동의까지 드러내며 증거로 낼지, 사본으로 항소(1심 판결에 불복해 다시 재판해 달라고 하는 것)부터 걸고 원본을 아껴 둘지 정한다",
  case46: "파쇄 트럭이 오기 전에 에코를 되살리고, 빈칸 옆의 점이 가리키는 곳과 에코가 지목한 '빠진 사람'을 어떻게 기록할지 정한다",
  case47: "181명이 추석 안에 받는 길과 31명을 끝까지 넣는 길 사이에서, 대출 서류가 아니라 밥값 장부와 죽은 사람의 수첩으로만 남은 피해를 어떻게 셀지 정합니다.",
  case48: "플로우온과 똑같은 모양의 대출 앞에서, 이번에는 지워지지 않는 반대 의견을 쓸지, 조건을 붙여 승인할지, 서명을 넘겨 칸을 비울지 정합니다. 반대 의견은 남지만, 그 대가로 214명의 10월 급여가 흔들립니다.",
  case49: "33층으로 올라가기 전날, 모두가 건넨 것과 에코의 마지막 계산과 회장의 전화를 안고, 빈 서명란에 누구의 이름이 들어가야 하는지 내일 가져갈 답을 정한다",
  final: "플로우온 심사 보고서의 빈 서명란에 누구의 이름이 있어야 했는지 확정한다",
};

export const seasonCasesBase = [
  {
    id: "case01",
    label: "사건 01",
    title: "72시간",
    trigger: "책임 / 보호 / 부당함",
    status: "PLAYABLE",
    summary:
      "플로우온의 현금이 72시간 뒤 바닥난다. 훈련용 사례라고 했지만, 3년 전 당신이 은행에서 혼자 반대했던 바로 그 대출이다.",
  },
  {
    id: "case02",
    label: "사건 02",
    title: "가짜 신호",
    trigger: "신뢰 / 정의 / 애정",
    status: "LOCKED",
    summary:
      "계약직 동료가 유출자로 지목된다. 새어 나갔다는 파일은 플로우온 대출 심사 보고서 원본이고, 접속 기록은 사람이 만든 것처럼 깔끔하다.",
  },
  {
    id: "case03",
    label: "사건 03",
    title: "경쟁자의 반격",
    trigger: "경쟁 / 인정 / 호기심",
    status: "LOCKED",
    summary:
      "노바웍스 입찰에서 오진우와 같은 자료로 겨룬다. 이 입찰 자체가 플로우온의 손실을 다른 회사 장부로 옮기는 통로일 수 있다.",
  },
  {
    id: "case04",
    label: "사건 04",
    title: "치러야 할 대가",
    trigger: "보상 / 책임 / 질서",
    status: "LOCKED",
    summary:
      "돌봄 플랫폼 온새의 심사 점수 3% 부족은 우연이 아니다. 그 3%는 KD은행이 갑자기 앞당긴 대출 상환 일정이 만들어 냈다.",
  },
  {
    id: "case05",
    label: "사건 05",
    title: "범인은 없었다",
    trigger: "시스템 / 호기심 / 무력감",
    status: "LOCKED",
    summary:
      "명백한 악인은 없다. 모두가 규정대로 움직였고, 그 규정을 맨 위에서 누르고 있던 것은 3년 전 계약서 한 장이다.",
  },
  {
    id: "case06",
    label: "사건 06",
    title: "같은 방의 사람",
    trigger: "경쟁 / 애정 / 자기 인식",
    status: "LOCKED",
    summary:
      "경쟁자 오진우가 무너진다. 그를 몰아붙인 압박 조건은 당신의 실험과 같은 번호를 쓰고 있었다.",
  },
  {
    id: "case07",
    label: "사건 07",
    title: "되갚는 자리",
    trigger: "부당함 / 신뢰 / 선택",
    status: "LOCKED",
    summary:
      "징계가 아니라 인사다. 48시간 뒤면 당신은 240km 밖 지점에 있고, 파일은 여기 남는다. 그 48시간에 누가 손을 내미는지가 이 사건이다.",
  },
  {
    id: "case08",
    label: "사건 08",
    title: "돈의 흔적",
    trigger: "복수 / 욕망 / 부당함",
    status: "LOCKED",
    summary:
      "좌천된 지점의 휴면 계좌(오래 거래가 끊긴 계좌) 하나가 분기마다 자문료를 받아 서울의 갤러리로 보낸다. 사람은 욕망을 갖고, 욕망은 돈을 쓰고, 돈은 흔적을 남긴다.",
  },
  {
    id: "case09",
    label: "사건 09",
    title: "두 장의 손익계산서",
    trigger: "애정 / 책임 / 보상",
    status: "LOCKED",
    summary:
      "플로우온이 다시 72시간 앞에 선다. 이번 안건은 청산(회사를 정리해 없애는 절차)이다. 회사를 살리는 계산서와 무너뜨린 사람을 벌하는 계산서를 한 테이블에 올려야 한다.",
  },
  {
    id: "case10",
    label: "사건 10",
    title: "멈추지 못하는 사람",
    trigger: "애정 / 무력감 / 선택",
    status: "LOCKED",
    summary:
      "이긴 다음 날 청구서가 온다. 3년간 피해자 명단을 혼자 들고 있던 사람이 쓰러지고, 그 명단은 공식 기록이 아니라 나흘 뒤 폐기된다.",
  },
  {
    id: "case11",
    label: "사건 11",
    title: "모두가 보는 방",
    trigger: "두려움 / 분노 / 웃음",
    status: "LOCKED",
    summary:
      "3년 전 사라진 반대 의견이 기사가 되고, 당신은 국정감사(국회가 공개적으로 따져 묻는 자리) 참고인석에 앉게 된다. 증인석의 윤상혁 자리는 비어 있다.",
  },
  {
    id: "case12",
    label: "사건 12",
    title: "1,740번째 사람",
    trigger: "분노 / 웃음 / 애도",
    status: "LOCKED",
    summary:
      "그룹이 300억 자율 배상안을 내놓는다. 조건은 다시는 소송하지 않겠다는 서명이다. 처음으로 피해자들의 가게와 공장과 추모공원으로 간다.",
  },
  {
    id: "case13",
    label: "사건 13",
    title: "혁신의 얼굴",
    trigger: "분노 / 웃음 / 연대",
    status: "LOCKED",
    summary:
      "국정감사(국회가 공개적으로 따져 묻는 자리) 뒤 여론을 돌리려는 그룹이 혁신위원회를 만들고, 반대 의견을 쓴 당신에게 광고의 얼굴이 되어 달라고 한다. 대본의 마지막 문장은 '과거는 모두 정리되었습니다'다.",
  },
  {
    id: "case14",
    label: "사건 14",
    title: "착한 펀드",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "그룹이 은행 창구에서 은퇴자에게 '상생 펀드'를 팝니다. 펀드가 사들이는 것은 그룹의 부실채권과 플로우온 대출의 남은 조각이고, 판매 대본에는 도윤하가 3년 전 쓰던 문장이 그대로 있습니다.",
  },
  {
    id: "case15",
    label: "사건 15",
    title: "정규직 심사",
    trigger: "기쁨 / 분노 / 웃음 / 슬픔",
    status: "LOCKED",
    summary:
      "3년차 계약직 이민서에게 정규직 전환 제안이 옵니다. 조건은 유출 소동 때 사라진 11초를 자기 실수로 인정하는 확인서 서명이고, 면접 날은 동생의 수능 날입니다.",
  },
  {
    id: "case16",
    label: "사건 16",
    title: "무인 창고",
    trigger: "분노 / 웃음 / 애도 / 기쁨",
    status: "LOCKED",
    summary:
      "플로우온 풀필먼트센터가 리스로 물류 로봇 120대를 들이고, 야간조 80명은 새벽 문자 한 통으로 계약 종료를 통보받는다. 첫 새벽에 컵라면을 뜯어 주던 강태민의 사건이다.",
  },
  {
    id: "case17",
    label: "사건 17",
    title: "수첩의 이름들",
    trigger: "책임 / 웃음 / 애도",
    status: "LOCKED",
    summary:
      "그룹 법무팀이 반재욱의 수첩을 회사 기록물이라며 당신의 징계 증거로 쓰려 한다. 넘기기 전에, 그가 20년 동안 내보낸 47명을 한 명씩 찾아간다.",
  },
  {
    id: "case18",
    label: "사건 18",
    title: "스카우트",
    trigger: "경쟁 / 웃음 / 애정",
    status: "LOCKED",
    summary:
      "브릿지은행이 KD은행의 부실채권(돌려받기 어려워진 대출) 묶음을 사들이려 하고, 그 팀장 자리를 오진우에게 내민다. 연봉 두 배, 그리고 KD를 벨 수 있는 칼이다.",
  },
  {
    id: "case19",
    label: "사건 19",
    title: "종이의 무게",
    trigger: "웃음 / 분노 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "전산에 없는 원본이 있는 회기동 헌책방 2층이 철거됩니다. 철거일은 국회의 자료 보존 기간 사흘 전으로 당겨졌고, 종이의 주인 임경수는 병원에 있습니다.",
  },
  {
    id: "case20",
    label: "사건 20",
    title: "에코의 업데이트",
    trigger: "슬픔 / 웃음 / 분노 / 기쁨",
    status: "LOCKED",
    summary:
      "에코가 새 AI 심사 엔진 노아로 교체되고 판단 기록은 초기화됩니다. 그런데 노아는 바로 그 기록으로, 동의 없이 배웠습니다.",
  },
  {
    id: "case21",
    label: "사건 21",
    title: "첫 번째 참가자",
    trigger: "기쁨 / 웃음 / 슬픔 / 분노",
    status: "LOCKED",
    summary:
      "노아가 배운 기록의 맨 아래 줄에, 당신보다 먼저 트리거랩을 거친 사람의 이름이 있다. 그는 지금 제주 구좌에서 귤 창고를 고친 게스트하우스를 하고, 자기 반응이 실험 자료였다는 걸 모른다.",
  },
  {
    id: "case22",
    label: "사건 22",
    title: "인턴 문하준",
    trigger: "기쁨 / 분노 / 애도",
    status: "LOCKED",
    summary:
      "문하준이 겨울방학 인턴으로 강서지점에 온다. 같은 주, 어머니와 기술자들이 다시 연 공장 끝까지정밀의 시설자금(기계나 설비를 사는 데 쓰는 돈) 신청을 AI 심사 엔진 노아가 0.8초 만에 거절한다. 사유는 세상을 떠난 아버지의 이름이다.",
  },
  {
    id: "case23",
    label: "사건 23",
    title: "주주총회",
    trigger: "분노 / 웃음 / 연대",
    status: "LOCKED",
    summary:
      "윤상혁을 사내이사(회사 경영에 직접 참여하는 이사)로 올리는 정기 주주총회가 열린다. 한 주씩 산 3,118명이 위임장을 들고 여의도 대강당 뒷줄을 채운다. 발언 시간은 1분이다.",
  },
  {
    id: "case24",
    label: "사건 24",
    title: "마지막 출근",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "주주총회 사흘 뒤 월요일, 트리거랩 해체 공지가 뜹니다. 사유는 '성과 없음'. 마지막 일주일 동안 책상이 하나씩 비고, 옥상에서 한서윤이 절반만 고백하고, 33층에서 백아린이 봉투 하나를 건넵니다.",
  },
  {
    id: "case25",
    label: "사건 25",
    title: "오지 않은 사람",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "올라오라던 밤, 33층에 윤상혁은 없습니다. 만우절 아침의 인사 공지는 그를 KD캐피탈 대표이사로 올리고, 트리거랩 여섯 명을 여섯 곳으로 흩어 놓습니다. 당신의 새 자리는 바로 그 사람의 아래입니다.",
  },
  {
    id: "case26",
    label: "사건 26",
    title: "골조만 남은 건물",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "윤상혁의 첫 안건은 15층에서 멈춘 평택 오피스텔입니다. 타워크레인 꼭대기에는 임금 석 달 치를 못 받은 반장이 앉아 있고, 연장 의견서의 작성자 칸에는 벌써 당신 이름이, 대표이사 칸에는 '해당 없음'이 인쇄돼 있습니다.",
  },
  {
    id: "case27",
    label: "사건 27",
    title: "동네 금고",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "금요일 밤 캡처 한 장에 군산 새봄신협 앞으로 300명이 줄을 섭니다. 남궁솔 전무는 줄 선 사람들의 이름을 다 알고, 나준혁은 번호표에 도장을 찍고, 소문의 말풍선은 KD캐피탈 사내 메신저와 똑같습니다.",
  },
  {
    id: "case28",
    label: "사건 28",
    title: "약관의 글씨",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "KD생명 콜센터로 3주 동안 지원을 나간 도윤하가 받은 첫 통화 목록에 끝까지정밀 조합원 채도훈이 있습니다. 선반 사고로 두 손가락의 감각을 잃은 그의 보험금 4,200만 원이 6.5포인트 조항 하나로 거절됐고, 도윤하는 그 거절을 3분짜리 대본으로 읽어야 합니다.",
  },
  {
    id: "case29",
    label: "사건 29",
    title: "마리나의 밤",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "해온파트너스 자문료의 마지막 행방을 쫓아 서하린과 싱가포르로 갑니다. KD캐피탈의 부실 대출 4,270억을 한 묶음으로 사 가려는 라운드힐 캐피탈, 그 계약서 맨 뒤 부속서에 윤상혁의 새 자리가 있습니다. 그리고 거래의 마지막 조건은 당신의 서명입니다.",
  },
  {
    id: "case30",
    label: "사건 30",
    title: "여섯 명의 단체방",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "흩어진 여섯이 한 달 만에 헌책방 1층에 모입니다. 트리거랩 참가자 63명의 반응 기록이 채용 점수 회사 핏스코어로 18억에 팔렸고, A-017은 이민서입니다. 움직이려면 모두 자기 자리를 걸어야 하고, 반재욱은 처음으로 자기 이름을 지웁니다.",
  },
  {
    id: "case31",
    label: "사건 31",
    title: "검사역",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "금융감독원 정기검사가 KD캐피탈에 들어옵니다. 검사역 한지우는 윤상혁이 고른 대응 담당인 당신을 믿지 않습니다. 닷새 동안 번호 붙은 질문이 쏟아지고, 폐기 예정 상자와 세 번 떨어진 서류철, 사라진 15쪽의 사연이 확인자 서명란 앞으로 모입니다.",
  },
  {
    id: "case32",
    label: "사건 32",
    title: "압수수색",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "서울중앙지검이 33층과 KD캐피탈을 동시에 압수수색합니다. 나은호 검사는 당신을 참고인으로 부르지만, 상자에서는 당신 이름이 제일 많이 나오고 당신이 쓴 적 없는 서명까지 나옵니다.",
  },
  {
    id: "case33",
    label: "사건 33",
    title: "보호받을 권리",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "백아린이 금융감독원에 공익신고를 낸 지 사흘, 그룹은 해고와 영업비밀 누설 고소와 사택 퇴거 통보를 한꺼번에 보냅니다. 짐 상자 스물세 개, 안양 수선집 벽의 사원증 액자, 시루떡을 들고 온 문가을, 그리고 입회인 칸이 비어 있는 합의서.",
  },
  {
    id: "case34",
    label: "사건 34",
    title: "아버지의 수첩",
    trigger: "애정 / 분노 / 웃음 / 슬픔",
    status: "LOCKED",
    summary:
      "윤상혁의 딸 윤서진이 아버지 서재에서 찾은 2023년 수첩을 들고 온다. '0412 — 반대 의견 — 보관 X'. 아버지를 지키고 싶다는 딸과, 그 한 줄 바로 아래 빨간 잉크로 적힌 딸의 중간고사 일정. 검사는 모레 오전 10시까지 수첩을 내지 않으면 딸을 부르겠다고 한다.",
  },
  {
    id: "case35",
    label: "사건 35",
    title: "장마",
    trigger: "분노 / 웃음 / 애도 / 기쁨",
    status: "LOCKED",
    summary:
      "시간당 110mm 폭우에 망원시장과 인천 끝까지정밀이 함께 잠긴다. 모두가 모래주머니를 나르는 동안, AI 심사 엔진(대출 신청을 자동으로 판단하는 인공지능 프로그램) 노아는 물에 잠겼다는 이유로 수해 긴급 대출을 거절한다.",
  },
  {
    id: "case36",
    label: "사건 36",
    title: "회장의 식탁",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "서도경 회장이 한남동 자택 식탁에 당신을 부릅니다. 이름을 아무도 못 외우는 요리 아홉 접시 사이로 제안이 나옵니다. 윤상혁 한 사람에게 모든 책임을 지우고 개혁 완료를 선언하자는 것, 그 대가는 준법감시인(회사가 법과 규정을 지키는지 안에서 감시하는 책임자) 자리입니다.",
  },
  {
    id: "case37",
    label: "사건 37",
    title: "유출",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "열대야의 새벽, 트리거랩 반응 기록 38만 줄이 통째로 인터넷에 올라온다. 열세 명이 망설인 초까지 전부. 누가 흘렸는지, 누가 다치는지, 그리고 퍼진 기록은 이제 누구의 것인지.",
  },
  {
    id: "case38",
    label: "사건 38",
    title: "원고 1,740명",
    trigger: "분노 / 웃음 / 슬픔 / 연대",
    status: "LOCKED",
    summary:
      "피해자 집단소송의 첫 변론. 피고석에는 대형 로펌 변호사 여덟 명, 원고석에는 공익 변호사 한 명과 떡집 사장 한 명. 그룹은 서류 없는 212명을 원고에서 빼려 하고, 유출된 당신의 반응 기록으로 당신의 증언을 흔든다.",
  },
  {
    id: "case39",
    label: "사건 39",
    title: "편집실의 밤",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "다큐멘터리 방송 전날 밤, KD 쪽 광고 14개가 빠지며 '참고 의견'에 정확히 20분이 적혀 옵니다. 상암동 방송국 편집실에서 아침 10시 납품까지, 무엇을 자르고 누구의 얼굴을 가릴지 정합니다.",
  },
  {
    id: "case40",
    label: "사건 40",
    title: "적합도 점수",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "채용 평가 회사 핏스코어가 트리거랩 반응 기록으로 만든 조직 적합도(사람이 회사에 얼마나 잘 맞을지 매긴 점수)로 수천 명을 면접도 없이 떨어뜨린다. 문하준은 주말 아르바이트에서 41점을 받는다. 모델이 가장 크게 감점하는 것은 망설임이고, 부적합의 기준점은 당신의 기록이다.",
  },
  {
    id: "case41",
    label: "사건 41",
    title: "두 번째 청문회",
    trigger: "분노 / 웃음 / 질문",
    status: "LOCKED",
    summary:
      "작년 가을 빈 의자였던 윤상혁이 이번에는 청문회(국회가 증인을 불러 한 사건을 집중해서 따져 묻는 자리) 증인석에 나온다. 준비해 온 대답은 '기억나지 않습니다' 하나. 당신에게 주어진 것은 1분과 질문 하나다.",
  },
  {
    id: "case42",
    label: "사건 42",
    title: "경포의 불꽃",
    trigger: "기쁨 / 웃음 / 분노 / 슬픔",
    status: "LOCKED",
    summary:
      "두 번째 청문회 다음 주, 나준혁의 '휴가 명령서'로 모두가 경포 불꽃축제에 갑니다. 숙소는 옛 해온 펜션, 지금은 여다인의 물결스테이. 금요일 저녁 7시 4분, 연체 한 번 없던 그에게 자동 회수 문자가 오고, 그날 밤 방파제 아래에서 모두가 무엇이 자기를 멈추지 못하게 했는지 말합니다.",
  },
  {
    id: "case43",
    label: "사건 43",
    title: "이사회",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "KD금융그룹 이사회가 윤상혁 해임안(이사를 자리에서 물러나게 하는 안건)을 올립니다. 표를 던지는 사람은 회장과 사외이사(회사 밖에서 와서 경영진을 감시하는 이사) 일곱, 모두 여덟. 안건 설명서에 2023년 이사회는 한 줄도 없고, 회장은 마지막 한 표에 조건을 붙입니다.",
  },
  {
    id: "case44",
    label: "사건 44",
    title: "1심 선고",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "해온파트너스 자문료(조언값이라며 주고받은 돈) 배임(맡은 일을 저버려 회사에 손해를 끼친 죄) 사건의 1심 선고 날. 선고 전날 피해자인 KD은행이 처벌불원서(처벌을 원하지 않는다는 서류)를 냈고, 판결문 43분 동안 재판장은 '다만'을 스물세 번 말합니다.",
  },
  {
    id: "case45",
    label: "사건 45",
    title: "마지막 종이",
    trigger: "슬픔 / 웃음 / 분노 / 기쁨",
    status: "LOCKED",
    summary:
      "임경수가 세상을 떠납니다. 사흘 동안의 빈소, 고인 흉을 보며 웃는 조문객들, 영정 옆에 놓인 그룹의 조화와 종이를 내놓으라는 법무팀의 요구서. 셋째 날 새벽, 손녀 임소율이 할아버지가 남긴 봉투를 엽니다. 반대 의견서 뒷장의 원본, 그리고 그가 썼다가 지운 '동의'.",
  },
  {
    id: "case46",
    label: "사건 46",
    title: "에코의 귀환",
    trigger: "웃음 / 분노 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "트리거랩 반납 서버가 파쇄되기 스무 시간 전, 이민서가 에코를 되살립니다. 돌아온 에코는 설계 로그(실험을 어떻게 짤지 바꾼 날짜와 사람을 남긴 기록) 3,412건을 다시 계산해 빈칸마다 찍힌 점 하나를 찾아내고, 3년 동안 계산에서 빠져 있던 사람으로 당신을 지목합니다.",
  },
  {
    id: "case47",
    label: "사건 47",
    title: "1년 뒤 추석",
    trigger: "기쁨 / 웃음 / 슬픔 / 분노",
    status: "LOCKED",
    summary:
      "사건 12로부터 꼭 1년, 가을떡방의 추석 대목에 모두가 다시 앞치마를 두릅니다. 2차 배상 기준은 서류 없는 212명 중 181명을 받아들였고, 남은 31명에게는 '확인 불가'가 찍혔습니다. 끝까지정밀의 첫 흑자 날, 문성호의 서랍에서 '갚을 곳'이라는 수첩이 나옵니다. 이름은 서른한 개입니다.",
  },
  {
    id: "case48",
    label: "사건 48",
    title: "새로 쓰는 반대 의견",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "추석 밤, KD캐피탈 임시 심사위원회에 도심 15분 배송 회사 루프나우의 290억 대출이 올라옵니다. 계약서 제7조는 2023-0412와 쉼표까지 같고, 서명란 다섯 칸 가운데 하나에 처음으로 당신 이름이 인쇄돼 있습니다. 투자 마감까지 남은 시간은 하룻밤입니다.",
  },
  {
    id: "case49",
    label: "사건 49",
    title: "33층으로",
    trigger: "분노 / 웃음 / 슬픔 / 기쁨",
    status: "LOCKED",
    summary:
      "심사위원회 다음 날, 윤상혁이 내일 밤 33층 옛 그룹전략실에서 빈 서명란 이야기를 하자고 합니다. 떡방에서는 모두가 들고 갈 물건을 건네고, B2의 옛 단말에서는 관리자 칸에 점 하나가 찍힌 후임 관리자 지정서가 당신 이름을 기다립니다. 회장은 받으라고 전화하고, 한서윤은 그 칸에 누구의 이름을 적을지 오늘 밤 정하자고 합니다.",
  },
  {
    id: "final",
    label: "마지막 사건",
    title: "빈 서명란",
    trigger: "자기 인식 / 조종 / 선택",
    status: "LOCKED",
    summary:
      "플로우온 심사 보고서의 서명란은 3년째 비어 있다. 그 칸을 비워 둔 사람이 트리거랩을 만들었고, 당신을 여기로 보냈다.",
  },
];
