-- The LLM reading of a free-input card arrives after the card has resolved, so
-- it cannot ride along in the `decision_log` the case row carries -- at least
-- not for the last card of a case, which is still in flight when that row is
-- written. This table takes it on its own, one row per analysed card.
--
-- It holds no player prose. `free_text` is not a column here and must never
-- become one: the analysis is what the model said about the sentence, not the
-- sentence.
create table if not exists public.free_text_analyses (
  id bigint generated by default as identity primary key,
  event_id text,
  session_id text not null,
  session_code text,
  run_id text,
  case_id text not null,
  node_id text not null,
  choice_id text,
  analysis jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index if not exists free_text_analyses_event_id_idx
  on public.free_text_analyses (event_id) where event_id is not null;
create index if not exists free_text_analyses_run_idx
  on public.free_text_analyses (run_id, case_id);

alter table public.free_text_analyses enable row level security;

-- Insert only, and never readable by anon: the rows exist to tune the prompt,
-- not to be served back to a client.
drop policy if exists "public can insert free text analyses" on public.free_text_analyses;
create policy "public can insert free text analyses" on public.free_text_analyses
for insert to anon
with check (
  length(session_id) between 8 and 128
  and length(node_id) between 1 and 120
  and jsonb_typeof(analysis) = 'object'
);

-- Same rate limit and session check every other telemetry table goes through.
-- `validate_telemetry_insert` branches on TG_TABLE_NAME and falls through to
-- the shared checks for a table it does not name, which is what this one wants.
drop trigger if exists validate_free_text_analyses_insert on public.free_text_analyses;
create trigger validate_free_text_analyses_insert
  before insert on public.free_text_analyses
  for each row execute function public.validate_telemetry_insert();

notify pgrst, 'reload schema';
