-- 참가자 게시판: a nickname and a short post, from anyone who plays.
--
-- Every other player-authored string in this schema is either private to the
-- device (the handoff note) or anonymised before it leaves it (`player_name` is
-- sent as '익명 분석관', and feedback is gated on consent). This table is the
-- deliberate exception: the point of a board is that the nickname and the words
-- are published. That makes it the only table here a spammer has a reason to
-- write to, so the defences are on the table rather than in the client.
--
-- Five of them, cheapest first:
--   1. Shape. A nickname of 2-24 characters and a body of 2-300, neither of
--      them only whitespace.
--   2. No links. A short note about a game does not need one, and a link is
--      what almost every automated post is actually for. Rejecting them costs
--      a player nothing and removes the payload.
--   3. Pace. One post per 30 seconds and ten per hour per writer, counted in
--      the same `telemetry_rate_limits` table the telemetry trigger uses, under
--      a `board:` key so a busy board cannot exhaust a run's telemetry budget
--      or the other way round.
--   4. Repeats. The same body from the same writer inside six hours is accepted
--      and dropped rather than refused, so a retrying client sees success and
--      the board does not gain a second copy.
--   5. Replay. `event_id` is unique when present, so a queue that sends twice
--      writes once.
--
-- `hidden` is the moderation handle: it is not writable by anon, and a hidden
-- row stops being readable. Nothing in the app sets it; it is for a human with
-- the service role and a reason.

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  event_id text,
  session_id text not null,
  nickname text not null,
  body text not null,
  hidden boolean not null default false,
  created_at timestamptz not null default now()
);

create unique index if not exists board_posts_event_id_idx
  on public.board_posts (event_id) where event_id is not null;
create index if not exists board_posts_recent_idx
  on public.board_posts (created_at desc) where not hidden;

alter table public.board_posts enable row level security;

-- The row filter and the column grant are a pair, the same way the ranking's
-- are: `session_id`, `event_id` and `hidden` stay invisible to anon even though
-- the row is public, so a reader cannot tell two posts came from one device.
revoke all on public.board_posts from anon;
revoke all on public.board_posts from authenticated;

drop policy if exists "public can read visible board posts" on public.board_posts;
create policy "public can read visible board posts" on public.board_posts
for select to anon
using (not hidden);

drop policy if exists "public can write board posts" on public.board_posts;
create policy "public can write board posts" on public.board_posts
for insert to anon
with check (
  length(session_id) between 8 and 128
  and length(btrim(nickname)) between 2 and 24
  and length(btrim(body)) between 2 and 300
  and hidden = false
);

grant select (id, nickname, body, created_at) on public.board_posts to anon;
grant insert (event_id, session_id, nickname, body) on public.board_posts to anon;

-- The board's own trigger rather than a branch in `validate_telemetry_insert`:
-- its limits are an order of magnitude tighter than telemetry's 120/hour, and
-- mixing the two would mean one number could only ever be wrong for one of
-- them. Locals are `v_`-prefixed because a PL/pgSQL name that matches a column
-- of a table the function writes to raises 42702 and blocks every insert --
-- which is exactly what happened to `validate_telemetry_insert` once.
create or replace function public.validate_board_post_insert()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_headers jsonb;
  v_actor_key text;
  v_window_started timestamptz;
  v_request_count integer;
  v_nickname text;
  v_body text;
begin
  v_nickname := btrim(new.nickname);
  v_body := btrim(new.body);

  if length(v_nickname) not between 2 and 24 then
    raise exception 'board nickname must be 2-24 characters';
  end if;
  if length(v_body) not between 2 and 300 then
    raise exception 'board post must be 2-300 characters';
  end if;
  if v_body ~* '(https?://|www\.|[a-z0-9-]+\.(com|net|org|io|kr|co|xyz|top|ru|cn)\b)' then
    raise exception 'board post must not contain a link';
  end if;

  new.nickname := v_nickname;
  new.body := v_body;
  new.hidden := false;

  begin
    v_headers := coalesce(current_setting('request.headers', true)::jsonb, '{}'::jsonb);
  exception when others then
    v_headers := '{}'::jsonb;
  end;
  v_actor_key := 'board:' || left(coalesce(nullif(v_headers->>'x-forwarded-for', ''), new.session_id), 190);

  -- Accepted and dropped, not refused: a client that retries a post it already
  -- landed gets a success and the board stays as it was.
  if exists (
    select 1 from public.board_posts
    where session_id = new.session_id
      and body = new.body
      and created_at > now() - interval '6 hours'
  ) then
    return null;
  end if;

  select window_started_at, request_count
    into v_window_started, v_request_count
    from public.telemetry_rate_limits
   where actor_key = v_actor_key;

  if v_window_started is not null
     and now() - v_window_started < interval '1 hour'
     and v_request_count >= 10 then
    raise exception 'board rate limit exceeded';
  end if;

  if exists (
    select 1 from public.board_posts
    where session_id = new.session_id
      and created_at > now() - interval '30 seconds'
  ) then
    raise exception 'board posts must be at least 30 seconds apart';
  end if;

  insert into public.telemetry_rate_limits (actor_key, window_started_at, request_count)
  values (v_actor_key, now(), 1)
  on conflict (actor_key) do update
  set request_count = case
        when now() - telemetry_rate_limits.window_started_at >= interval '1 hour' then 1
        else telemetry_rate_limits.request_count + 1
      end,
      window_started_at = case
        when now() - telemetry_rate_limits.window_started_at >= interval '1 hour' then now()
        else telemetry_rate_limits.window_started_at
      end;

  return new;
end;
$$;

revoke execute on function public.validate_board_post_insert() from public;
revoke execute on function public.validate_board_post_insert() from anon;
revoke execute on function public.validate_board_post_insert() from authenticated;

drop trigger if exists validate_board_posts_insert on public.board_posts;
create trigger validate_board_posts_insert
  before insert on public.board_posts
  for each row execute function public.validate_board_post_insert();

-- Retention covers the board too. Adding a count to the returned row changes the
-- function's row type, which `create or replace` refuses (42P13), so the old one
-- is dropped first. The argument list is untouched, so a schedule that calls
-- `purge_old_telemetry()` needs no edit -- it just gets one more column back.
drop function if exists public.purge_old_telemetry(interval);

create function public.purge_old_telemetry(retention interval default interval '180 days')
returns table (sessions_deleted bigint, feedback_deleted bigint, errors_deleted bigint, board_posts_deleted bigint)
language plpgsql
security definer
set search_path = public
as $$
declare
  cutoff timestamptz;
begin
  if retention < interval '30 days' then
    raise exception 'telemetry retention must be at least 30 days';
  end if;
  cutoff := now() - retention;

  delete from public.playtest_sessions where completed_at < cutoff;
  get diagnostics sessions_deleted = row_count;

  delete from public.playtest_feedback where created_at < cutoff;
  get diagnostics feedback_deleted = row_count;

  delete from public.app_error_logs where created_at < cutoff;
  get diagnostics errors_deleted = row_count;

  delete from public.board_posts where created_at < cutoff;
  get diagnostics board_posts_deleted = row_count;

  return next;
end;
$$;

revoke all on function public.purge_old_telemetry(interval) from public;
revoke all on function public.purge_old_telemetry(interval) from anon;
revoke all on function public.purge_old_telemetry(interval) from authenticated;

notify pgrst, 'reload schema';
